final List<Map<String, dynamic>> addressListTable = [
  {
    'address_id': 1,
    'address_name': 'Rumah Wisma Teduh',
    'address_detail': 'Jl. Lorem Ipsum 1 No. 2',
    'isBookmarked': true,
  },
  {
    'address_id': 2,
    'address_name': 'Wisma Mentari Indah',
    'address_detail': 'Jl. Mawar Raya No. 12',
    'isBookmarked': false,
  },
  {
    'address_id': 3,
    'address_name': 'Kost Anggrek Satu',
    'address_detail': 'Jl. Anggrek No. 5',
    'isBookmarked': true,
  },
  {
    'address_id': 4,
    'address_name': 'Paviliun Melati',
    'address_detail': 'Jl. Melati Selatan No. 8',
    'isBookmarked': false,
  },
  {
    'address_id': 5,
    'address_name': 'Kost Putri Sakura',
    'address_detail': 'Jl. Sakura Timur No. 21',
    'isBookmarked': false,
  },
  {
    'address_id': 6,
    'address_name': 'Wisma Seruni',
    'address_detail': 'Jl. Seruni No. 10',
    'isBookmarked': false,
  },
  {
    'address_id': 7,
    'address_name': 'Kost Kenanga',
    'address_detail': 'Jl. Kenanga Barat No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 8,
    'address_name': 'Asrama Mahasiswa Harmoni',
    'address_detail': 'Jl. Harmoni No. 99',
    'isBookmarked': false,
  },
  {
    'address_id': 9,
    'address_name': 'Villa Lestari',
    'address_detail': 'Jl. Lestari Indah No. 7',
    'isBookmarked': false,
  },
  {
    'address_id': 10,
    'address_name': 'Kost Lavender',
    'address_detail': 'Jl. Lavender No. 15',
    'isBookmarked': false,
  },
  {
    'address_id': 11,
    'address_name': 'Wisma Cempaka',
    'address_detail': 'Jl. Cempaka Putih No. 22',
    'isBookmarked': false,
  },
  {
    'address_id': 12,
    'address_name': 'Kost Bunga Raya',
    'address_detail': 'Jl. Bunga Raya No. 6',
    'isBookmarked': false,
  },
  {
    'address_id': 13,
    'address_name': 'Asrama Putra Wijaya',
    'address_detail': 'Jl. Wijaya Kusuma No. 30',
    'isBookmarked': false,
  },
  {
    'address_id': 14,
    'address_name': 'Kost Taman Sari',
    'address_detail': 'Jl. Taman Sari No. 18',
    'isBookmarked': false,
  },
  {
    'address_id': 15,
    'address_name': 'Rumah Singgah Sejahtera',
    'address_detail': 'Jl. Sejahtera No. 55',
    'isBookmarked': false,
  },
  {
    'address_id': 16,
    'address_name': 'Pondok Damai',
    'address_detail': 'Jl. Damai Indah No. 14',
    'isBookmarked': false,
  },
  {
    'address_id': 17,
    'address_name': 'Villa Nirwana',
    'address_detail': 'Jl. Nirwana No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 18,
    'address_name': 'Wisma Elok',
    'address_detail': 'Jl. Elok Raya No. 11',
    'isBookmarked': false,
  },
  {
    'address_id': 19,
    'address_name': 'Kost Damai Putri',
    'address_detail': 'Jl. Damai Putri No. 4',
    'isBookmarked': false,
  },
  {
    'address_id': 20,
    'address_name': 'Asrama Cendekia',
    'address_detail': 'Jl. Cendekia No. 2',
    'isBookmarked': false,
  },
];