final List<Map<String, dynamic>> addressListTable = [
  {
    'address_id': 1,
    'address_name': 'Rumah Wisma Teduh',
    'address_detail': 'Jl. Lorem Ipsum 1 No. 2',
    'isBookmarked': true,
  },
  {
    'address_id': 2,
    'address_name': 'Wisma Mentari Indah',
    'address_detail': 'Jl. Mawar Raya No. 12',
    'isBookmarked': false,
  },
  {
    'address_id': 3,
    'address_name': 'Kost Anggrek Satu',
    'address_detail': 'Jl. Anggrek No. 5',
    'isBookmarked': true,
  },
  {
    'address_id': 4,
    'address_name': 'Paviliun Melati',
    'address_detail': 'Jl. Melati Selatan No. 8',
    'isBookmarked': false,
  },
  {
    'address_id': 5,
    'address_name': 'Kost Putri Sakura',
    'address_detail': 'Jl. Sakura Timur No. 21',
    'isBookmarked': false,
  },
  {
    'address_id': 6,
    'address_name': 'Wisma Seruni',
    'address_detail': 'Jl. Seruni No. 10',
    'isBookmarked': false,
  },
  {
    'address_id': 7,
    'address_name': 'Kost Kenanga',
    'address_detail': 'Jl. Kenanga Barat No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 8,
    'address_name': 'Asrama Mahasiswa Harmoni',
    'address_detail': 'Jl. Harmoni No. 99',
    'isBookmarked': false,
  },
  {
    'address_id': 9,
    'address_name': 'Villa Lestari',
    'address_detail': 'Jl. Lestari Indah No. 7',
    'isBookmarked': false,
  },
  {
    'address_id': 10,
    'address_name': 'Kost Lavender',
    'address_detail': 'Jl. Lavender No. 15',
    'isBookmarked': false,
  },
  {
    'address_id': 11,
    'address_name': 'Wisma Cempaka',
    'address_detail': 'Jl. Cempaka Putih No. 22',
    'isBookmarked': false,
  },
  {
    'address_id': 12,
    'address_name': 'Kost Bunga Raya',
    'address_detail': 'Jl. Bunga Raya No. 6',
    'isBookmarked': false,
  },
  {
    'address_id': 13,
    'address_name': 'Asrama Putra Wijaya',
    'address_detail': 'Jl. Wijaya Kusuma No. 30',
    'isBookmarked': false,
  },
  {
    'address_id': 14,
    'address_name': 'Kost Taman Sari',
    'address_detail': 'Jl. Taman Sari No. 18',
    'isBookmarked': false,
  },
  {
    'address_id': 15,
    'address_name': 'Rumah Singgah Sejahtera',
    'address_detail': 'Jl. Sejahtera No. 55',
    'isBookmarked': false,
  },
  {
    'address_id': 16,
    'address_name': 'Pondok Damai',
    'address_detail': 'Jl. Damai Indah No. 14',
    'isBookmarked': false,
  },
  {
    'address_id': 17,
    'address_name': 'Villa Nirwana',
    'address_detail': 'Jl. Nirwana No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 18,
    'address_name': 'Wisma Elok',
    'address_detail': 'Jl. Elok Raya No. 11',
    'isBookmarked': false,
  },
  {
    'address_id': 19,
    'address_name': 'Kost Damai Putri',
    'address_detail': 'Jl. Damai Putri No. 4',
    'isBookmarked': false,
  },
  {
    'address_id': 20,
    'address_name': 'Asrama Cendekia',
    'address_detail': 'Jl. Cendekia No. 2',
    'isBookmarked': false,
  },
  {
    'address_id': 21,
    'address_name': 'Kost Flamboyan',
    'address_detail': 'Jl. Flamboyan Indah No. 5',
    'isBookmarked': false,
  },
  {
    'address_id': 22,
    'address_name': 'Wisma Permata Hijau',
    'address_detail': 'Jl. Permata Hijau No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 23,
    'address_name': 'Pondok Harapan',
    'address_detail': 'Jl. Harapan Baru No. 7',
    'isBookmarked': false,
  },
  {
    'address_id': 24,
    'address_name': 'Asrama Sakura',
    'address_detail': 'Jl. Sakura Barat No. 8',
    'isBookmarked': false,
  },
  {
    'address_id': 25,
    'address_name': 'Villa Kenyamanan',
    'address_detail': 'Jl. Kenyamanan No. 21',
    'isBookmarked': false,
  },
  {
    'address_id': 26,
    'address_name': 'Kost Ceria',
    'address_detail': 'Jl. Ceria Raya No. 14',
    'isBookmarked': false,
  },
  {
    'address_id': 27,
    'address_name': 'Wisma Pelita',
    'address_detail': 'Jl. Pelita Harapan No. 6',
    'isBookmarked': false,
  },
  {
    'address_id': 28,
    'address_name': 'Pondok Harmoni',
    'address_detail': 'Jl. Harmoni Indah No. 12',
    'isBookmarked': false,
  },
  {
    'address_id': 29,
    'address_name': 'Asrama Mawar',
    'address_detail': 'Jl. Mawar Putih No. 9',
    'isBookmarked': false,
  },
  {
    'address_id': 30,
    'address_name': 'Kost Pelangi',
    'address_detail': 'Jl. Pelangi No. 2',
    'isBookmarked': false,
  },
  {
    'address_id': 31,
    'address_name': 'Wisma Bahagia',
    'address_detail': 'Jl. Bahagia Raya No. 1',
    'isBookmarked': false,
  },
  {
    'address_id': 32,
    'address_name': 'Villa Mentari',
    'address_detail': 'Jl. Mentari Timur No. 10',
    'isBookmarked': false,
  },
  {
    'address_id': 33,
    'address_name': 'Kost Harmonis',
    'address_detail': 'Jl. Harmonis No. 17',
    'isBookmarked': false,
  },
  {
    'address_id': 34,
    'address_name': 'Paviliun Sejahtera',
    'address_detail': 'Jl. Sejahtera Raya No. 5',
    'isBookmarked': false,
  },
  {
    'address_id': 35,
    'address_name': 'Kost Amanah',
    'address_detail': 'Jl. Amanah No. 3',
    'isBookmarked': false,
  },
  {
    'address_id': 36,
    'address_name': 'Wisma Santai',
    'address_detail': 'Jl. Santai Indah No. 4',
    'isBookmarked': false,
  },
  {
    'address_id': 37,
    'address_name': 'Asrama Damai Lestari',
    'address_detail': 'Jl. Lestari Raya No. 11',
    'isBookmarked': false,
  },
  {
    'address_id': 38,
    'address_name': 'Kost Elok Asri',
    'address_detail': 'Jl. Elok Asri No. 8',
    'isBookmarked': false,
  },
  {
    'address_id': 39,
    'address_name': 'Villa Surya',
    'address_detail': 'Jl. Surya Mandala No. 13',
    'isBookmarked': false,
  },
  {
    'address_id': 40,
    'address_name': 'Pondok Anggrek',
    'address_detail': 'Jl. Anggrek Lestari No. 6',
    'isBookmarked': false,
  },
];