final List<Map<String, dynamic>> businessListTable = [
  {
    'business_id': 1,
    'business_name': 'Ristorante',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorante.png',
    'business_rating': 4.5,
    'business_distance': 3.98,
    'business_address': 'Jl. Raya Mekarsari No. 128, RT 05 RW 09, Kelurahan Sukamaju, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 2,
    'business_name': 'Supermarket Aja',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketaja.png',
    'business_rating': 4.8,
    'business_distance': 1.43,
    'business_address': 'Jl. Pasar Induk No. 456, RT 03 RW 07, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17134',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '20-30 menit',
  },
  {
    'business_id': 3,
    'business_name': 'Umami Hana Restaurant',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/umamihana.png',
    'business_rating': 4.8,
    'business_distance': 4.11,
    'business_address': 'Jl. Kuliner No. 789, RT 02 RW 08, Kelurahan Aren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 11, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 4,
    'business_name': 'Pasar Murah',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/pasarmurah.png',
    'business_rating': 4.7,
    'business_distance': 2.38,
    'business_address': 'Jl. Ekonomi No. 12, RT 01 RW 05, Kelurahan Bintara, Bekasi, Jawa Barat 17134',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 18, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 5,
    'business_name': 'Sabor do Sol',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sabordosol.png',
    'business_rating': 4.7,
    'business_distance': 2.18,
    'business_address': 'Jl. Sunset No. 98, RT 06 RW 02, Kelurahan Jakasampurna, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 12, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '40-60 menit',
  },
  {
    'business_id': 6,
    'business_name': 'Glow Kitchen',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/glowkitchen.png',
    'business_rating': 4.7,
    'business_distance': 2.11,
    'business_address': 'Jl. Sehat No. 35, RT 03 RW 06, Kelurahan Jatibening, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 7,
    'business_name': 'sehatBang',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatbang.png',
    'business_rating': 4.5,
    'business_distance': 2.48,
    'business_address': 'Jl. Fit Street No. 44, RT 02 RW 01, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 8,
    'business_name': 'HarvestMart Supermarket',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/harvestmart.png',
    'business_rating': 4.8,
    'business_distance': 3.28,
    'business_address': 'Jl. Harvest No. 22, RT 04 RW 03, Kelurahan Jaka Setia, Bekasi, Jawa Barat 17147',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '20-30 menit',
  },
  {
    'business_id': 9,
    'business_name': 'Fit Market',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/fitmarket.png',
    'business_rating': 4.5,
    'business_distance': 1.98,
    'business_address': 'Jl. Patriot No. 65, RT 04 RW 06, Kelurahan Kayuringin Jaya, Bekasi, Jawa Barat 17144',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 10,
    'business_name': 'ZestMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/zestmart.png',
    'business_rating': 4.9,
    'business_distance': 4.00,
    'business_address': 'Jl. Ir. H. Juanda No. 100, RT 02 RW 05, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 11,
    'business_name': 'Rasa Nusantara',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/rasanusantara.png',
    'business_rating': 4.2,
    'business_distance': 1.11,
    'business_address': 'Jl. Nusantara Raya No. 123, RT 01 RW 03, Kelurahan Margahayu, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 12,
    'business_name': 'Ristorante Cabangan',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'business_rating': 4.3,
    'business_distance': 5.17,
    'business_address': 'Jl. Cabang Dua No. 88, RT 06 RW 08, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17148',
    'business_open_hour': DateTime(2025, 1, 1, 11, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '40-60 menit',
  },
  {
    'business_id': 13,
    'business_name': 'Lina Elit Healthy Resto',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/linaelit.png',
    'business_rating': 4.3,
    'business_distance': 4.55,
    'business_address': 'Jl. Kesehatan Sejahtera No. 45, RT 02 RW 06, Kelurahan Mustikasari, Bekasi, Jawa Barat 17158',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 14,
    'business_name': 'Green Spoon',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/greenspoon.png',
    'business_rating': 4.2,
    'business_distance': 0.91,
    'business_address': 'Jl. Lingkungan Hijau No. 1, RT 03 RW 05, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17148',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '20-30 menit',
  },
  {
    'business_id': 15,
    'business_name': 'Le Pappillon Blue',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/lepapillonbleu.png',
    'business_rating': 4.7,
    'business_distance': 0.68,
    'business_address': 'Jl. Perancis Raya No. 22, RT 01 RW 01, Kelurahan Jakasampurna, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 16,
    'business_name': 'Sehatku',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatku.png',
    'business_rating': 4.9,
    'business_distance': 4.56,
    'business_address': 'Jl. Sehat Abadi No. 89, RT 06 RW 09, Kelurahan Jatiluhur, Bekasi, Jawa Barat 17137',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 17,
    'business_name': 'Ladang Sehat',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/ladangsehat.png',
    'business_rating': 4.7,
    'business_distance': 0.34,
    'business_address': 'Jl. Pertanian Hijau No. 12, RT 02 RW 04, Kelurahan Jatiasih, Bekasi, Jawa Barat 17423',
    'business_open_hour': DateTime(2025, 1, 1, 6, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 18,
    'business_name': 'Pasar Famgro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/famgro.png',
    'business_rating': 4.9,
    'business_distance': 2.13,
    'business_address': 'Jl. Pasar Modern No. 77, RT 05 RW 03, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 19,
    'business_name': 'Sehat Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/sehatmart.png',
    'business_rating': 4.9,
    'business_distance': 0.48,
    'business_address': 'Jl. Pasar Sehat No. 33, RT 04 RW 07, Kelurahan Jatibening, Bekasi, Jawa Barat 17412',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '20-30 menit',
  },
  {
    'business_id': 20,
    'business_name': 'HealthyCareMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/healthycaremart.png',
    'business_rating': 4.8,
    'business_distance': 5.75,
    'business_address': 'Jl. Kesehatan Peduli No. 55, RT 03 RW 08, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17124',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '40-60 menit',
  },
  {
    'business_id': 21,
    'business_name': 'Vitagro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/vitagro.png',
    'business_rating': 4.9,
    'business_distance': 2.22,
    'business_address': 'Jl. Organik Sehat No. 19, RT 01 RW 09, Kelurahan Bojong Rawalumbu, Bekasi, Jawa Barat 17116',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '25-35 menit',
  },
  {
    'business_id': 22,
    'business_name': 'Supermarket Aja Cabang',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketajacabang.png',
    'business_rating': 4.9,
    'business_distance': 5.92,
    'business_address': 'Jl. Pusat Belanja No. 88, RT 06 RW 03, Kelurahan Margahayu, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '30-45 menit',
  },
  {
    'business_id': 23,
    'business_name': 'Ristorante Cabang Kenanga',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'business_rating': 4.3,
    'business_distance': 6.58,
    'business_address': 'Jl. Kenanga Raya No. 45, RT 02 RW 02, Kelurahan Bekasi Jaya, Bekasi, Jawa Barat 17112',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 12, 0),
    'estimated_delivery': '30-45 menit',
  },
];