final List<Map<String, dynamic>> businessProductListTable = [
  // Verdura Italiana (12 Products)
  {'business_id': 1, 'product_id': 1, 'add_ons_id': 1},
  {'business_id': 1, 'product_id': 1, 'add_ons_id': 2},
  {'business_id': 1, 'product_id': 1, 'add_ons_id': 3},

  {'business_id': 1, 'product_id': 2, 'add_ons_id': 4},
  {'business_id': 1, 'product_id': 2, 'add_ons_id': 5},
  
  {'business_id': 1, 'product_id': 3, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 4, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 5, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 6, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 7, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 8, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 9, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 10, 'add_ons_id': null},

  {'business_id': 1, 'product_id': 23, 'add_ons_id': null},
  {'business_id': 1, 'product_id': 24, 'add_ons_id': null},

  // Supermarket Harmoni (12 Products)
  {'business_id': 2, 'product_id': 11, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 12, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 13, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 14, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 15, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 16, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 17, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 18, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 19, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 20, 'add_ons_id': null},

  {'business_id': 2, 'product_id': 25, 'add_ons_id': null},
  {'business_id': 2, 'product_id': 26, 'add_ons_id': null},

  // Aozora Sehat Kitchen (12 Products)
  {'business_id': 3, 'product_id': 27, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 28, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 33, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 34, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 35, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 36, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 37, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 38, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 39, 'add_ons_id': null},
  {'business_id': 3, 'product_id': 40, 'add_ons_id': null},

  // Pasar Murah (10 Products)
  {'business_id': 4, 'product_id': 41, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 42, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 43, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 44, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 45, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 46, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 47, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 48, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 49, 'add_ons_id': null},
  {'business_id': 4, 'product_id': 50, 'add_ons_id': null},

  // Verde Brazil (12 Products)
  {'business_id': 5, 'product_id': 21, 'add_ons_id': 7},
  {'business_id': 5, 'product_id': 22, 'add_ons_id': 6},

  {'business_id': 5, 'product_id': 51, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 52, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 53, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 54, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 55, 'add_ons_id': null},

  {'business_id': 5, 'product_id': 56, 'add_ons_id': 8},
  {'business_id': 5, 'product_id': 56, 'add_ons_id': 9},
  
  {'business_id': 5, 'product_id': 57, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 58, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 59, 'add_ons_id': null},
  {'business_id': 5, 'product_id': 60, 'add_ons_id': null},

  // Glow Kitchen (10 Products)
  {'business_id': 6, 'product_id': 61, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 62, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 63, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 64, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 65, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 66, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 67, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 68, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 69, 'add_ons_id': null},
  {'business_id': 6, 'product_id': 70, 'add_ons_id': null},

  // sehatBang (10 Products)
  {'business_id': 7, 'product_id': 71, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 72, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 73, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 74, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 75, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 76, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 77, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 78, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 79, 'add_ons_id': null},
  {'business_id': 7, 'product_id': 80, 'add_ons_id': null},

  // HarvestMart Supermarket (12 Products)
  {'business_id': 8, 'product_id': 29, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 30, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 81, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 82, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 83, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 84, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 85, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 86, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 87, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 88, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 89, 'add_ons_id': null},
  {'business_id': 8, 'product_id': 90, 'add_ons_id': null},

  // Fit Market (10 Products)
  {'business_id': 9, 'product_id': 91, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 92, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 93, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 94, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 95, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 96, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 97, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 98, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 99, 'add_ons_id': null},
  {'business_id': 9, 'product_id': 100, 'add_ons_id': null},

  // ZestMart (10 Products)
  {'business_id': 10, 'product_id': 101, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 102, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 103, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 104, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 105, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 106, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 107, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 108, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 109, 'add_ons_id': null},
  {'business_id': 10, 'product_id': 110, 'add_ons_id': null},

  // Dapur Sehat Nusantara (10 Products)
  {'business_id': 11, 'product_id': 111, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 112, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 113, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 114, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 115, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 116, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 117, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 118, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 119, 'add_ons_id': null},
  {'business_id': 11, 'product_id': 120, 'add_ons_id': null},

  // Verdura Italiana Centro (10 Products)
  {'business_id': 12, 'product_id': 1, 'add_ons_id': 1},
  {'business_id': 12, 'product_id': 1, 'add_ons_id': 2},
  {'business_id': 12, 'product_id': 1, 'add_ons_id': 3},

  {'business_id': 12, 'product_id': 2, 'add_ons_id': 4},
  {'business_id': 12, 'product_id': 2, 'add_ons_id': 5},
  
  {'business_id': 12, 'product_id': 3, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 4, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 5, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 6, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 7, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 8, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 9, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 10, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 23, 'add_ons_id': null},
  {'business_id': 12, 'product_id': 24, 'add_ons_id': null},

  // Lina Elit Healthy Resto (10 Products)
  {'business_id': 13, 'product_id': 121, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 122, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 123, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 124, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 125, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 126, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 127, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 128, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 129, 'add_ons_id': null},
  {'business_id': 13, 'product_id': 130, 'add_ons_id': null},

  // Green Spoon (10 Products)
  {'business_id': 14, 'product_id': 131, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 132, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 133, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 134, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 135, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 136, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 137, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 138, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 139, 'add_ons_id': null},
  {'business_id': 14, 'product_id': 140, 'add_ons_id': null},
  
  // Cuisine Pure (10 Products)
  {'business_id': 15, 'product_id': 141, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 142, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 143, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 144, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 145, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 146, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 147, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 148, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 149, 'add_ons_id': null},
  {'business_id': 15, 'product_id': 150, 'add_ons_id': null},

  // Sehatku (10 Products)
  {'business_id': 16, 'product_id': 151, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 152, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 153, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 154, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 155, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 156, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 157, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 158, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 159, 'add_ons_id': null},
  {'business_id': 16, 'product_id': 160, 'add_ons_id': null},

  // Ladang Sehat (10 Products)
  {'business_id': 17, 'product_id': 161, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 162, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 163, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 164, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 165, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 166, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 167, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 168, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 169, 'add_ons_id': null},
  {'business_id': 17, 'product_id': 170, 'add_ons_id': null},

  // Pasar Famgro (12 Products)
  {'business_id': 18, 'product_id': 31, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 32, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 171, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 172, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 173, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 174, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 175, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 176, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 177, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 178, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 179, 'add_ons_id': null},
  {'business_id': 18, 'product_id': 180, 'add_ons_id': null},

  // Sehat Mart (10 Products)
  {'business_id': 19, 'product_id': 181, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 182, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 183, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 184, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 185, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 186, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 187, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 188, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 189, 'add_ons_id': null},
  {'business_id': 19, 'product_id': 190, 'add_ons_id': null},

  // HealthyCareMart (10 Products)
  {'business_id': 20, 'product_id': 191, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 192, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 193, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 194, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 195, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 196, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 197, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 198, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 199, 'add_ons_id': null},
  {'business_id': 20, 'product_id': 200, 'add_ons_id': null},

  // Vitagro (10 Products)
  {'business_id': 21, 'product_id': 201, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 202, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 203, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 204, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 205, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 206, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 207, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 208, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 209, 'add_ons_id': null},
  {'business_id': 21, 'product_id': 210, 'add_ons_id': null},

  // Supermarket Harmoni Tunas (10 Products)
  {'business_id': 22, 'product_id': 11, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 12, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 13, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 14, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 15, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 16, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 17, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 18, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 19, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 20, 'add_ons_id': null},

  {'business_id': 22, 'product_id': 25, 'add_ons_id': null},
  {'business_id': 22, 'product_id': 26, 'add_ons_id': null},

    // Verdura Italiana Kenanga (12 Products)
  {'business_id': 23, 'product_id': 1, 'add_ons_id': 1},
  {'business_id': 23, 'product_id': 1, 'add_ons_id': 2},
  {'business_id': 23, 'product_id': 1, 'add_ons_id': 3},

  {'business_id': 23, 'product_id': 2, 'add_ons_id': 4},
  {'business_id': 23, 'product_id': 2, 'add_ons_id': 5},
  
  {'business_id': 23, 'product_id': 3, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 4, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 5, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 6, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 7, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 8, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 9, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 10, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 23, 'add_ons_id': null},
  {'business_id': 23, 'product_id': 24, 'add_ons_id': null},
];