final List<Map<String, dynamic>> businessListTable = [
  {
    'business_id': 1,
    'business_name': 'Ristorante',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorante.png',
    'business_rating': 4.5,
    'business_distance': 3.98,
    'business_address': 'Jl. Raya Mekarsari No. 128, RT 05 RW 09, Kelurahan Sukamaju, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 0, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 59),
    'estimated_delivery': '30-45 menit',
    'service_fee': 8000,
  },
  {
    'business_id': 2,
    'business_name': 'Supermarket Aja',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketaja.png',
    'business_rating': 4.8,
    'business_distance': 1.43,
    'business_address': 'Jl. Pasar Induk No. 456, RT 03 RW 07, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17134',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '20-30 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 3,
    'business_name': 'Umami Hana Restaurant',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/umamihana.png',
    'business_rating': 4.8,
    'business_distance': 4.11,
    'business_address': 'Jl. Kuliner No. 789, RT 02 RW 08, Kelurahan Aren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 11, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 4,
    'business_name': 'Pasar Murah',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/pasarmurah.png',
    'business_rating': 4.7,
    'business_distance': 2.38,
    'business_address': 'Jl. Ekonomi No. 12, RT 01 RW 05, Kelurahan Bintara, Bekasi, Jawa Barat 17134',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 18, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 4000,
  },
  {
    'business_id': 5,
    'business_name': 'Sabor do Sol',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sabordosol.png',
    'business_rating': 4.7,
    'business_distance': 2.18,
    'business_address': 'Jl. Sunset No. 98, RT 06 RW 02, Kelurahan Jakasampurna, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 12, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '40-60 menit',
    'service_fee': 7000,
  },
  {
    'business_id': 6,
    'business_name': 'Glow Kitchen',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/glowkitchen.png',
    'business_rating': 4.7,
    'business_distance': 2.11,
    'business_address': 'Jl. Sehat No. 35, RT 03 RW 06, Kelurahan Jatibening, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 7,
    'business_name': 'sehatBang',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatbang.png',
    'business_rating': 4.5,
    'business_distance': 2.48,
    'business_address': 'Jl. Fit Street No. 44, RT 02 RW 01, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 8,
    'business_name': 'HarvestMart Supermarket',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/harvestmart.png',
    'business_rating': 4.8,
    'business_distance': 3.28,
    'business_address': 'Jl. Harvest No. 22, RT 04 RW 03, Kelurahan Jaka Setia, Bekasi, Jawa Barat 17147',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '20-30 menit',
    'service_fee': 4500,
  },
  {
    'business_id': 9,
    'business_name': 'Fit Market',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/fitmarket.png',
    'business_rating': 4.5,
    'business_distance': 1.98,
    'business_address': 'Jl. Patriot No. 65, RT 04 RW 06, Kelurahan Kayuringin Jaya, Bekasi, Jawa Barat 17144',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 5500,
  },
  {
    'business_id': 10,
    'business_name': 'ZestMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/zestmart.png',
    'business_rating': 4.9,
    'business_distance': 4.00,
    'business_address': 'Jl. Ir. H. Juanda No. 100, RT 02 RW 05, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 11,
    'business_name': 'Rasa Nusantara',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/rasanusantara.png',
    'business_rating': 4.2,
    'business_distance': 1.11,
    'business_address': 'Jl. Nusantara Raya No. 123, RT 01 RW 03, Kelurahan Margahayu, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 12,
    'business_name': 'Ristorante Cabangan',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'business_rating': 4.3,
    'business_distance': 5.17,
    'business_address': 'Jl. Cabang Dua No. 88, RT 06 RW 08, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17148',
    'business_open_hour': DateTime(2025, 1, 1, 11, 0),
    'business_close_hour': DateTime(2025, 1, 1, 23, 0),
    'estimated_delivery': '40-60 menit',
    'service_fee': 7000,
  },
  {
    'business_id': 13,
    'business_name': 'Lina Elit Healthy Resto',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/linaelit.png',
    'business_rating': 4.3,
    'business_distance': 4.55,
    'business_address': 'Jl. Kesehatan Sejahtera No. 45, RT 02 RW 06, Kelurahan Mustikasari, Bekasi, Jawa Barat 17158',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 14,
    'business_name': 'Green Spoon',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/greenspoon.png',
    'business_rating': 4.2,
    'business_distance': 0.91,
    'business_address': 'Jl. Lingkungan Hijau No. 1, RT 03 RW 05, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17148',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '20-30 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 15,
    'business_name': 'Le Pappillon Blue',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/lepapillonbleu.png',
    'business_rating': 4.7,
    'business_distance': 0.68,
    'business_address': 'Jl. Perancis Raya No. 22, RT 01 RW 01, Kelurahan Jakasampurna, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 5500,
  },
  {
    'business_id': 16,
    'business_name': 'Sehatku',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatku.png',
    'business_rating': 4.9,
    'business_distance': 4.56,
    'business_address': 'Jl. Sehat Abadi No. 89, RT 06 RW 09, Kelurahan Jatiluhur, Bekasi, Jawa Barat 17137',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 17,
    'business_name': 'Ladang Sehat',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/ladangsehat.png',
    'business_rating': 4.7,
    'business_distance': 0.34,
    'business_address': 'Jl. Pertanian Hijau No. 12, RT 02 RW 04, Kelurahan Jatiasih, Bekasi, Jawa Barat 17423',
    'business_open_hour': DateTime(2025, 1, 1, 6, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 18,
    'business_name': 'Pasar Famgro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/famgro.png',
    'business_rating': 4.9,
    'business_distance': 2.13,
    'business_address': 'Jl. Pasar Modern No. 77, RT 05 RW 03, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17111',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 19,
    'business_name': 'Sehat Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/sehatmart.png',
    'business_rating': 4.9,
    'business_distance': 0.48,
    'business_address': 'Jl. Pasar Sehat No. 33, RT 04 RW 07, Kelurahan Jatibening, Bekasi, Jawa Barat 17412',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '20-30 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 20,
    'business_name': 'HealthyCareMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/healthycaremart.png',
    'business_rating': 4.8,
    'business_distance': 5.75,
    'business_address': 'Jl. Kesehatan Peduli No. 55, RT 03 RW 08, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17124',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '40-60 menit',
    'service_fee': 7000,
  },
  {
    'business_id': 21,
    'business_name': 'Vitagro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/vitagro.png',
    'business_rating': 4.9,
    'business_distance': 2.22,
    'business_address': 'Jl. Organik Sehat No. 19, RT 01 RW 09, Kelurahan Bojong Rawalumbu, Bekasi, Jawa Barat 17116',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 22,
    'business_name': 'Supermarket Aja Cabang',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketajacabang.png',
    'business_rating': 4.9,
    'business_distance': 5.92,
    'business_address': 'Jl. Pusat Belanja No. 88, RT 06 RW 03, Kelurahan Margahayu, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 23,
    'business_name': 'Ristorante Cabang Kenanga',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'business_rating': 4.3,
    'business_distance': 6.58,
    'business_address': 'Jl. Kenanga Raya No. 45, RT 02 RW 02, Kelurahan Bekasi Jaya, Bekasi, Jawa Barat 17112',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 12, 0),
    'estimated_delivery': '30-45 menit',
    'service_fee': 6000,
  },
    {
    'business_id': 24,
    'business_name': 'Hijau Rasa',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/hijaurasa.webp',
    'business_rating': 4.7,
    'business_distance': 5.2,
    'business_address': 'Jl. Melati Indah No. 12, RT 03 RW 01, Kelurahan Bekasi Timur, Bekasi, Jawa Barat 17113',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 19, 0),
    'estimated_delivery': '10-20 menit',
    'service_fee': 3000,
  },
  {
    'business_id': 25,
    'business_name': 'Ladang Sehat Resto',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ladangsehatresto.webp',
    'business_rating': 4.5,
    'business_distance': 6.8,
    'business_address': 'Jl. Mawar Asri No. 21, RT 04 RW 05, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17114',
    'business_open_hour': DateTime(2025, 1, 1, 7, 30),
    'business_close_hour': DateTime(2025, 1, 1, 19, 30),
    'estimated_delivery': '15-25 menit',
    'service_fee': 4000,
  },
  {
    'business_id': 26,
    'business_name': 'Daun & Dapur',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/daun&dapur.webp',
    'business_rating': 4.2,
    'business_distance': 4.1,
    'business_address': 'Jl. Cempaka Raya No. 88, RT 01 RW 03, Kelurahan Jatiasih, Bekasi, Jawa Barat 17115',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '20-30 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 27,
    'business_name': 'Sehati Kitchen',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatikitchen.jpg',
    'business_rating': 4.6,
    'business_distance': 3.5,
    'business_address': 'Jl. Dahlia Utama No. 19, RT 05 RW 06, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17116',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '25-35 menit',
    'service_fee': 2000,
  },
  {
    'business_id': 28,
    'business_name': 'Rasa Alami',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/rasaalami.jpg',
    'business_rating': 4.8,
    'business_distance': 7.1,
    'business_address': 'Jl. Kemuning Permai No. 3, RT 02 RW 04, Kelurahan Pondok Ungu, Bekasi, Jawa Barat 17117',
    'business_open_hour': DateTime(2025, 1, 1, 6, 30),
    'business_close_hour': DateTime(2025, 1, 1, 20, 30),
    'estimated_delivery': '30-45 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 29,
    'business_name': 'FitBite',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/fitbite.jpg',
    'business_rating': 4.3,
    'business_distance': 2.9,
    'business_address': 'Jl. Anggrek Lestari No. 11, RT 06 RW 02, Kelurahan Mustika Jaya, Bekasi, Jawa Barat 17118',
    'business_open_hour': DateTime(2025, 1, 1, 11, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '5-15 menit',
    'service_fee': 1000,
  },
  {
    'business_id': 30,
    'business_name': 'Natura Bowl',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/naturabowl.jpg',
    'business_rating': 4.9,
    'business_distance': 3.3,
    'business_address': 'Jl. Flamboyan Raya No. 76, RT 01 RW 01, Kelurahan Jatisari, Bekasi, Jawa Barat 17119',
    'business_open_hour': DateTime(2025, 1, 1, 9, 30),
    'business_close_hour': DateTime(2025, 1, 1, 20, 30),
    'estimated_delivery': '10-25 menit',
    'service_fee': 3000,
  },
  {
    'business_id': 31,
    'business_name': 'SayurLoka',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sayurloka.jpg',
    'business_rating': 4.0,
    'business_distance': 6.0,
    'business_address': 'Jl. Teratai Baru No. 40, RT 03 RW 04, Kelurahan Bekasi Barat, Bekasi, Jawa Barat 17120',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 19, 0),
    'estimated_delivery': '15-30 menit',
    'service_fee': 4000,
  },
  {
    'business_id': 32,
    'business_name': 'Zen & Zest',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/zen&zest.jpg',
    'business_rating': 4.4,
    'business_distance': 4.7,
    'business_address': 'Jl. Wijaya Kusuma No. 22, RT 02 RW 02, Kelurahan Bintara, Bekasi, Jawa Barat 17121',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 19, 0),
    'estimated_delivery': '20-35 menit',
    'service_fee': 2000,
  },
  {
    'business_id': 33,
    'business_name': 'Santap Segar',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/santapsegar.jpg',
    'business_rating': 4.6,
    'business_distance': 2.4,
    'business_address': 'Jl. Kamboja Sejahtera No. 17, RT 05 RW 05, Kelurahan Pondok Gede, Bekasi, Jawa Barat 17122',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 19, 0),
    'estimated_delivery': '10-20 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 34,
    'business_name': 'Pasar Sehat Nusantara',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/pasarsehatnusantara.jpg',
    'business_rating': 4.3,
    'business_distance': 3.8,
    'business_address': 'Jl. Melati Indah No. 21, RT 03 RW 01, Kelurahan Harapan Jaya, Bekasi, Jawa Barat 17139',
    'business_open_hour': DateTime(2025, 1, 1, 7, 30),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '10-25 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 35,
    'business_name': 'Segar Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/segarmart.jpg',
    'business_rating': 4.7,
    'business_distance': 5.1,
    'business_address': 'Jl. Mawar Asri No. 4, RT 01 RW 02, Kelurahan Pekayon Jaya, Bekasi, Jawa Barat 17140',
    'business_open_hour': DateTime(2025, 1, 1, 8, 0),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '20-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 36,
    'business_name': 'Toko Organik Kita',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/tokoorganikkita.jpg',
    'business_rating': 4.5,
    'business_distance': 2.5,
    'business_address': 'Jl. Anggrek Lestari No. 5, RT 02 RW 04, Kelurahan Kayuringin Jaya, Bekasi, Jawa Barat 17141',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '10-20 menit',
    'service_fee': 4000,
  },
  {
    'business_id': 37,
    'business_name': 'Fresh Market Jaya',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/freshmarketjaya.jpg',
    'business_rating': 4.8,
    'business_distance': 6.3,
    'business_address': 'Jl. Cemara Baru No. 18, RT 04 RW 03, Kelurahan Duren Jaya, Bekasi, Jawa Barat 17142',
    'business_open_hour': DateTime(2025, 1, 1, 7, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 30),
    'estimated_delivery': '15-30 menit',
    'service_fee': 7000,
  },
  {
    'business_id': 38,
    'business_name': 'Hijau Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/hijaumart.jpg',
    'business_rating': 4.2,
    'business_distance': 4.6,
    'business_address': 'Jl. Cempaka Raya No. 12, RT 01 RW 02, Kelurahan Jatikramat, Bekasi, Jawa Barat 17143',
    'business_open_hour': DateTime(2025, 1, 1, 8, 45),
    'business_close_hour': DateTime(2025, 1, 1, 21, 30),
    'estimated_delivery': '25-40 menit',
    'service_fee': 3000,
  },
  {
    'business_id': 39,
    'business_name': 'Pasar Organik Maju',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/pasarorganikmaju.jpg',
    'business_rating': 4.6,
    'business_distance': 3.3,
    'business_address': 'Jl. Rambutan Hijau No. 9, RT 03 RW 01, Kelurahan Jatiasih, Bekasi, Jawa Barat 17144',
    'business_open_hour': DateTime(2025, 1, 1, 7, 15),
    'business_close_hour': DateTime(2025, 1, 1, 19, 45),
    'estimated_delivery': '5-15 menit',
    'service_fee': 8000,
  },
  {
    'business_id': 40,
    'business_name': 'Super Sehat Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supersehatmart.jpg',
    'business_rating': 4.4,
    'business_distance': 7.8,
    'business_address': 'Jl. Mangga Muda No. 25, RT 02 RW 04, Kelurahan Bojong Rawalumbu, Bekasi, Jawa Barat 17145',
    'business_open_hour': DateTime(2025, 1, 1, 9, 0),
    'business_close_hour': DateTime(2025, 1, 1, 22, 0),
    'estimated_delivery': '10-25 menit',
    'service_fee': 5000,
  },
  {
    'business_id': 41,
    'business_name': 'Bumi Segar Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/bumisegarmart.jpg',
    'business_rating': 4.0,
    'business_distance': 2.9,
    'business_address': 'Jl. Sawo Asri No. 7, RT 01 RW 03, Kelurahan Jatimulya, Bekasi, Jawa Barat 17146',
    'business_open_hour': DateTime(2025, 1, 1, 10, 0),
    'business_close_hour': DateTime(2025, 1, 1, 20, 0),
    'estimated_delivery': '20-35 menit',
    'service_fee': 6000,
  },
  {
    'business_id': 42,
    'business_name': 'Organik Keluarga Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/organikkeluargamart.jpg',
    'business_rating': 4.1,
    'business_distance': 3.5,
    'business_address': 'Jl. Durian Jaya No. 8, RT 04 RW 02, Kelurahan Mustika Jaya, Bekasi, Jawa Barat 17147',
    'business_open_hour': DateTime(2025, 1, 1, 7, 45),
    'business_close_hour': DateTime(2025, 1, 1, 21, 0),
    'estimated_delivery': '15-30 menit',
    'service_fee': 4000,
  },
  {
    'business_id': 43,
    'business_name': 'Sumber Sehat Market',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/sumbersehatmarket.jpg',
    'business_rating': 4.9,
    'business_distance': 6.0,
    'business_address': 'Jl. Pisang Raya No. 30, RT 06 RW 05, Kelurahan Margahayu, Bekasi, Jawa Barat 17148',
    'business_open_hour': DateTime(2025, 1, 1, 8, 15),
    'business_close_hour': DateTime(2025, 1, 1, 21, 45),
    'estimated_delivery': '10-20 menit',
    'service_fee': 7000,
  },
];