final List<Map<String, dynamic>> businessListTable = [
  {
    'business_id': 1,
    'business_name': 'Ristorante',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorante.png',
    'business_rating': 4.5,
    'business_distance': 3.98,
    'business_address': '123 Main St, Jakarta',
    'business_open_hours': '10:00 - 22:00',
  },
  {
    'business_id': 2,
    'business_name': 'Supermarket Aja',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketaja.png',
    'business_rating': 4.8,
    'business_distance': 1.43,
    'business_address': '456 Market Rd, Bandung',
    'business_open_hours': '08:00 - 21:00',
  },
  {
    'business_id': 3,
    'business_name': 'Umami Hana Restaurant',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/umamihana.png',
    'business_rating': 4.8,
    'business_distance': 4.11,
    'business_address': '789 Culinary Blvd, Surabaya',
    'business_open_hours': '11:00 - 23:00',
  },
  {
    'business_id': 4,
    'business_name': 'Pasar Murah',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/pasarmurah.png',
    'business_rating': 4.7,
    'business_distance': 2.38,
    'business_address': '12 Budget Lane, Semarang',
    'business_open_hours': '07:00 - 18:00',
  },
  {
    'business_id': 5,
    'business_name': 'Sabor do Sol',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sabordosol.png',
    'business_rating': 4.7,
    'business_distance': 2.18,
    'business_address': '98 Sunset Ave, Bali',
    'business_open_hours': '12:00 - 23:00',
  },
  {
    'business_id': 6,
    'business_name': 'Glow Kitchen',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/glowkitchen.png',
    'business_rating': 4.7,
    'business_distance': 2.11,
    'business_address': '35 Healthy Way, Yogyakarta',
    'business_open_hours': '09:00 - 21:00',
  },
  {
    'business_id': 7,
    'business_name': 'sehatBang',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatbang.png',
    'business_rating': 4.5,
    'business_distance': 2.48,
    'business_address': '44 Fit Street, Medan',
    'business_open_hours': '10:00 - 20:00',
  },
  {
    'business_id': 8,
    'business_name': 'HarvestMart Supermarket',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/harvestmart.png',
    'business_rating': 4.8,
    'business_distance': 3.28,
    'business_address': '77 Harvest Rd, Bogor',
    'business_open_hours': '07:00 - 22:00',
  },
  {
    'business_id': 9,
    'business_name': 'Fit Market',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/fitmarket.png',
    'business_rating': 4.5,
    'business_distance': 1.98,
    'business_address': '65 Gym Plaza, Depok',
    'business_open_hours': '08:00 - 20:00',
  },
  {
    'business_id': 10,
    'business_name': 'ZestMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/zestmart.png',
    'business_rating': 4.9,
    'business_distance': 4.00,
    'business_address': '100 Fresh Blvd, Bekasi',
    'business_open_hours': '07:00 - 21:00',
  },
  {
    'business_id': 11,
    'business_name': 'Rasa Nusantara',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/rasanusantara.png',
    'business_rating': 4.2,
    'business_distance': 1.11,
    'business_address': '123 Nusantara St, Jakarta',
    'business_open_hours': '10:00 - 22:00',
  },
  {
    'business_id': 12,
    'business_name': 'Ristorante Cabangan',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'business_rating': 4.3,
    'business_distance': 5.17,
    'business_address': '88 Cabangan Road, Jakarta',
    'business_open_hours': '11:00 - 23:00',
  },
  {
    'business_id': 13,
    'business_name': 'Lina Elit Healthy Resto',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/linaelit.png',
    'business_rating': 4.3,
    'business_distance': 4.55,
    'business_address': '45 Wellness Ave, Bandung',
    'business_open_hours': '09:00 - 21:00',
  },
  {
    'business_id': 14,
    'business_name': 'Green Spoon',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/greenspoon.png',
    'business_rating': 4.2,
    'business_distance': 0.91,
    'business_address': '1 Eco Street, Jakarta',
    'business_open_hours': '08:00 - 20:00',
  },
  {
    'business_id': 15,
    'business_name': 'Le Pappillon Blue',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/lepapillonbleu.png',
    'business_rating': 4.7,
    'business_distance': 0.68,
    'business_address': '22 French Lane, Jakarta',
    'business_open_hours': '10:00 - 22:00',
  },
  {
    'business_id': 16,
    'business_name': 'Sehatku',
    'business_type': 'restaurant',
    'business_image': 'assets/images/dummy/restaurant/sehatku.png',
    'business_rating': 4.9,
    'business_distance': 4.56,
    'business_address': '89 Healthy Blvd, Bandung',
    'business_open_hours': '07:00 - 21:00',
  },
  {
    'business_id': 17,
    'business_name': 'Ladang Sehat',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/ladangsehat.png',
    'business_rating': 4.7,
    'business_distance': 0.34,
    'business_address': '12 Green Farm Rd, Bogor',
    'business_open_hours': '06:00 - 20:00',
  },
  {
    'business_id': 18,
    'business_name': 'Pasar Famgro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/famgro.png',
    'business_rating': 4.9,
    'business_distance': 2.13,
    'business_address': '77 Market St, Depok',
    'business_open_hours': '07:00 - 21:00',
  },
  {
    'business_id': 19,
    'business_name': 'Sehat Mart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/sehatmart.png',
    'business_rating': 4.9,
    'business_distance': 0.48,
    'business_address': '33 Wellness Market, Jakarta',
    'business_open_hours': '08:00 - 20:00',
  },
  {
    'business_id': 20,
    'business_name': 'HealthyCareMart',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/healthycaremart.png',
    'business_rating': 4.8,
    'business_distance': 5.75,
    'business_address': '55 Health Ave, Tangerang',
    'business_open_hours': '09:00 - 22:00',
  },
  {
    'business_id': 21,
    'business_name': 'Vitagro',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/vitagro.png',
    'business_rating': 4.9,
    'business_distance': 2.22,
    'business_address': '19 Organic Plaza, Bandung',
    'business_open_hours': '08:00 - 20:00',
  },
  {
    'business_id': 22,
    'business_name': 'Supermarket Aja Cabang',
    'business_type': 'market',
    'business_image': 'assets/images/dummy/market/supermarketajacabang.png',
    'business_rating': 4.9,
    'business_distance': 5.92,
    'business_address': '88 Retail Center, Bekasi',
    'business_open_hours': '07:00 - 22:00',
  },
];