final List<Map<String, dynamic>> chatListTable = [
  {
    'chat_id': 1,
    'driver_id': 1,
    'is_user': true,
    'message_sent': 'Terima kasih banyak, makanannya sudah saya terima',
    'message_time': DateTime(2025, 3, 27, 16, 55),
  },
  {
    'chat_id': 2,
    'driver_id': 1,
    'is_user': false,
    'message_sent': 'Terima kasih juga, Pak!',
    'message_time': DateTime(2025, 3, 27, 16, 56),
  },
  {
    'chat_id': 3,
    'driver_id': 2,
    'is_user': true,
    'message_sent': 'Driver sudah sampai?',
    'message_time': DateTime(2025, 3, 28, 11, 15),
  },
  {
    'chat_id': 4,
    'driver_id': 2,
    'is_user': false,
    'message_sent': 'Saya sedang di depan rumah Anda.',
    'message_time': DateTime(2025, 3, 28, 11, 17),
  },
  {
    'chat_id': 5,
    'driver_id': 2,
    'is_user': false,
    'message_sent': 'https://drive.google.com/uc?export=download&id=10kJMcOs4of4REsF_Uy1mR34GspHaiLJz',
    'message_time': DateTime(2025, 3, 28, 11, 18),
  },
  {
    'chat_id': 6,
    'driver_id': 3,
    'is_user': false,
    'message_sent': 'Mohon ditunggu ya, saya lagi di jalan.',
    'message_time': DateTime(2025, 4, 1, 9, 10),
  },
  {
    'chat_id': 7,
    'driver_id': 3,
    'is_user': true,
    'message_sent': 'Siap, saya tunggu.',
    'message_time': DateTime(2025, 4, 1, 9, 12),
  },
  {
    'chat_id': 8,
    'driver_id': 4,
    'is_user': false,
    'message_sent': 'Maaf, pesanan Anda tidak dapat diproses karena stok habis.',
    'message_time': DateTime(2025, 4, 2, 14, 30),
  },
  {
    'chat_id': 9,
    'driver_id': 4,
    'is_user': true,
    'message_sent': 'Oh, tidak apa-apa. Terima kasih atas informasinya.',
    'message_time': DateTime(2025, 4, 2, 14, 35),
  },
    {
    'chat_id': 10,
    'driver_id': 6,
    'is_user': true,
    'message_sent': 'Selamat pagi, apakah pesanan saya sudah siap?',
    'message_time': DateTime(2025, 5, 12, 19, 03),
  },
  {
    'chat_id': 11,
    'driver_id': 6,
    'is_user': false,
    'message_sent': 'Selamat pagi! Pesanan Anda sudah siap dan sedang dalam perjalanan.',
    'message_time': DateTime(2025, 5, 12, 19, 05),
  },
  {
    'chat_id': 12,
    'driver_id': 6,
    'is_user': true,
    'message_sent': 'https://drive.google.com/uc?export=download&id=1v5Atq68A9taj6nKefUitO9gXPcOMdezl',
    'message_time': DateTime(2025, 5, 12, 19, 06),
  },
  {
    'chat_id': 13,
    'driver_id': 5,
    'is_user': true,
    'message_sent': 'Halo, kak! Apakah pesanan saya sudah dalam perjalanan?',
    'message_time': DateTime.now().subtract(const Duration(minutes: 9)),
  },
  {
    'chat_id': 14,
    'driver_id': 5,
    'is_user': false,
    'message_sent': 'Halo! Iya, pesanan sudah saya antar dan sedang dalam perjalanan.',
    'message_time': DateTime.now().subtract(const Duration(minutes: 8)),
  },
  {
    'chat_id': 15,
    'driver_id': 5,
    'is_user': true,
    'message_sent': 'Kalau sudah dekat, bisa dititipkan di resepsionis ya?',
    'message_time': DateTime.now().subtract(const Duration(minutes: 6)),
  },
  {
    'chat_id': 16,
    'driver_id': 5,
    'is_user': false,
    'message_sent': 'Baik, saya akan titipkan di resepsionis saat sampai.',
    'message_time': DateTime.now().subtract(const Duration(minutes: 4)),
  },
  {
    'chat_id': 17,
    'driver_id': 5,
    'is_user': true,
    'message_sent': 'Terima kasih banyak, kak! Hati-hati di jalan.',
    'message_time': DateTime.now().subtract(const Duration(minutes: 3)),
  },
  {
    'chat_id': 18,
    'driver_id': 5,
    'is_user': false,
    'message_sent': 'Sama-sama! Selamat menikmati makanannya!',
    'message_time': DateTime.now().subtract(const Duration(minutes: 2)),
  },
];
