final today = DateTime.now().subtract(const Duration(days: 1));

List<Map<String, dynamic>> historyOrderListTable = [
  {
    'history_id': 1,
    'business_id': 18,
    'address_id': 1,
    'driver_id': 2,
    'driver_note': 'Ditaruh didepan saja ya',
    'order_date': DateTime(2025, 6, 20, 8, 12),
    'estimated_arrival_time': null,
    'delivery_fee': 3500,
    'payment_method': 'QRIS Scan',
    'status': 'selesai',
  },
  {
    'history_id': 2,
    'business_id': 8,
    'address_id': 1,
    'driver_id': 6,
    'driver_note': null,
    'order_date': DateTime(2025, 6, 23, 6, 49),
    'estimated_arrival_time': null,
    'delivery_fee': 5500,
    'payment_method': 'Virtual Account',
    'status': 'selesai',
  },
  {
    'history_id': 3,
    'business_id': 3,
    'address_id': 1,
    'driver_id': 3,
    'driver_note': 'Mohon ditunggu di depan rumah',
    'order_date': DateTime(2025, 6, 24, 13, 39),
    'estimated_arrival_time': null,
    'delivery_fee': 4500,
    'payment_method': 'Pembayaran Tunai',
    'status': 'selesai',
  },
  {
    'history_id': 4,
    'business_id': 2,
    'address_id': 1,
    'driver_id': 1,
    'driver_note': null,
    'order_date': DateTime(2025, 6, 25, 14, 51),
    'estimated_arrival_time': null,
    'delivery_fee': 5500,
    'payment_method': 'QRIS Scan',
    'status': 'selesai',
  },
  {
    'history_id': 5,
    'business_id': 1,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': null,
    'order_date': DateTime(2025, 6, 26, 11, 24),
    'estimated_arrival_time': null,
    'delivery_fee': 6500,
    'payment_method': 'Virtual Account',
    'status': 'selesai',
  },
  {
    'history_id': 6,
    'business_id': 5,
    'address_id': 1,
    'driver_id': 4,
    'driver_note': 'Hati-hati licin di depan gang',
    'order_date': DateTime(2025, 6, 27, 14, 50),
    'estimated_arrival_time': null,
    'delivery_fee': 4500,
    'payment_method': 'Pembayaran Tunai',
    'status': 'selesai',
  },
  {
    'history_id': 7,
    'business_id': 2,
    'address_id': 1,
    'driver_id': 2,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 16, 20),
    'estimated_arrival_time': '15-20 menit',
    'delivery_fee': 2500,
    'payment_method': 'Pembayaran Tunai',
    'status': 'dikirim',
  },
  {
    'history_id': 8,
    'business_id': 2,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 16, 30),
    'estimated_arrival_time': '40-45 menit',
    'delivery_fee': 2500,
    'payment_method': 'Virtual Account',
    'status': 'diproses',
  },
  {
    'history_id': 9,
    'business_id': 25,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': 'Saya pakai jaket hijau',
    'order_date': DateTime(today.year, today.month, today.day, 16, 40),
    'estimated_arrival_time': '5-10 menit',
    'delivery_fee': 2500,
    'payment_method': 'QRIS Scan',
    'status': 'dikirim',
  },
  {
    'history_id': 10,
    'business_id': 1,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 16, 50),
    'estimated_arrival_time': '25-30 menit',
    'delivery_fee': 4500,
    'payment_method': 'Pembayaran Tunai',
    'status': 'diproses',
  },
  {
    'history_id': 11,
    'business_id': 22,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 16, 55),
    'estimated_arrival_time': '40-60 menit',
    'delivery_fee': 0,
    'payment_method': 'Virtual Account',
    'status': 'diproses',
  },
  {
    'history_id': 12,
    'business_id': 12,
    'address_id': 1,
    'driver_id': 5,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 17, 00),
    'estimated_arrival_time': '30-45 menit',
    'delivery_fee': 4500,
    'payment_method': 'QRIS Scan',
    'status': 'diproses',
  },
  {
    'history_id': 13,
    'business_id': 25,
    'address_id': 1,
    'driver_id': 8,
    'driver_note': 'taruh saja depan kamar',
    'order_date': DateTime(2025, 7, 3, 16, 47),
    'estimated_arrival_time': null,
    'delivery_fee': 7500,
    'payment_method': 'QRIS Scan',
    'status': 'selesai',
  },
  {
    'history_id': 14,
    'business_id': 25,
    'address_id': 1,
    'driver_id': 8,
    'driver_note': 'taruh saja depan kamar',
    'order_date': DateTime(today.year, today.month, today.day, 17, 05),
    'estimated_arrival_time': '15-25 menit',
    'delivery_fee': 7500,
    'payment_method': 'QRIS Scan',
    'status': 'diproses',
  },
  {
    'history_id': 15,
    'business_id': 21,
    'address_id': 1,
    'driver_id': 8,
    'driver_note': null,
    'order_date': DateTime(today.year, today.month, today.day, 17, 10),
    'estimated_arrival_time': '25-35 menit',
    'delivery_fee': 0,
    'payment_method': 'Pembayaran Tunai',
    'status': 'diproses',
  },
];