List<Map<String, dynamic>> historyOrderListTable = [
  {
    'history_id': 1,
    'business_id': 18,
    'driver_id': 2,
    'order_date': DateTime(2025, 3, 20, 8, 12),
    'address_receiver': 'Jl. Tradisional No. 10',
    'estimated_arrival_time': null,
    'service_fee': 1000,
    'delivery_fee': 3000,
    'payment_method': 'QRIS Scan',
    'status': 'selesai',
  },
  {
    'history_id': 2,
    'business_id': 8,
    'driver_id': 6,
    'order_date': DateTime(2025, 3, 23, 6, 49),
    'address_receiver': 'Jl. Panen Raya No. 7',
    'estimated_arrival_time': null,
    'service_fee': 2000,
    'delivery_fee': 5000,
    'payment_method': 'Virtual Account',
    'status': 'selesai',
  },
  {
    'history_id': 3,
    'business_id': 3,
    'driver_id': 3,
    'order_date': DateTime(2025, 3, 24, 13, 39),
    'address_receiver': 'Jl. Sakura Indah No. 88',
    'estimated_arrival_time': null,
    'service_fee': 3050,
    'delivery_fee': 4000,
    'payment_method': 'Pembayaran Tunai',
    'status': 'selesai',
  },
  {
    'history_id': 4,
    'business_id': 2,
    'driver_id': 1,
    'order_date': DateTime(2025, 3, 25, 14, 51),
    'address_receiver': 'Jl. Belanja No. 12',
    'estimated_arrival_time': null,
    'service_fee': 3000,
    'delivery_fee': 5000,
    'payment_method': 'QRIS Scan',
    'status': 'selesai',
  },
  {
    'history_id': 5,
    'business_id': 1,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 26, 11, 24),
    'address_receiver': 'Jl. Lorem Ipsum 1 No. 2',
    'estimated_arrival_time': null,
    'service_fee': 5600,
    'delivery_fee': 10000,
    'payment_method': 'Virtual Account',
    'status': 'selesai',
  },
  {
    'history_id': 6,
    'business_id': 5,
    'driver_id': 4,
    'order_date': DateTime(2025, 3, 27, 14, 50),
    'address_receiver': 'Jl. Matahari No. 5',
    'estimated_arrival_time': null,
    'service_fee': 5000,
    'delivery_fee': 10000,
    'payment_method': 'Pembayaran Tunai',
    'status': 'selesai',
  },
  {
    'history_id': 7,
    'business_id': 2,
    'driver_id': 2,
    'order_date': DateTime(2025, 3, 25, 16, 20),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '15-20 menit',
    'service_fee': 500,
    'delivery_fee': 2500,
    'payment_method': 'Pembayaran Tunai',
    'status': 'dikirim',
  },
    {
    'history_id': 8,
    'business_id': 2,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 25, 16, 30),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '40-45 menit',
    'service_fee': 9000,
    'delivery_fee': 1000,
    'payment_method': 'Virtual Account',
    'status': 'diproses',
  },
  {
    'history_id': 9,
    'business_id': 1,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 27, 16, 40),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '5-10 menit',
    'service_fee': 1000,
    'delivery_fee': 2000,
    'payment_method': 'QRIS Scan',
    'status': 'dikirim',
  },
  {
    'history_id': 10,
    'business_id': 1,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 27, 16, 50),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '25-30 menit',
    'service_fee': 8000,
    'delivery_fee': 2000,
    'payment_method': 'Pembayaran Tunai',
    'status': 'diproses',
  },
  {
    'history_id': 11,
    'business_id': 2,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 27, 16, 55),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '40-60 menit',
    'service_fee': 5000,
    'delivery_fee': 0,
    'payment_method': 'Virtual Account',
    'status': 'diproses',
  },
  {
    'history_id': 12,
    'business_id': 1,
    'driver_id': 5,
    'order_date': DateTime(2025, 3, 27, 17, 00),
    'address_receiver': 'Jl. Sehat Bahagia 2 No. 10',
    'estimated_arrival_time': '30-45 menit',
    'service_fee': 9000,
    'delivery_fee': 5000,
    'payment_method': 'QRIS Scan',
    'status': 'diproses',
  },
];