final List<Map<String, dynamic>> productListTable = [
  {
    'product_id': 1,
    'product_name': 'Insalata Caprese',
    'product_description': 'Tomat segar, mozzarella, dan daun basil disiram minyak zaitun. Hidangan khas Italia yang ringan dan menyegarkan.',
    'product_image': 'assets/images/dummy/food/ristorante/insalatacaprese.png',
    'product_price': 38000,
  },
  {
    'product_id': 2,
    'product_name': 'Zuppa di Verdure',
    'product_description': 'Sup sayur ala Italia dengan berbagai sayuran segar. Cocok untuk dinikmati saat cuaca dingin.',
    'product_image': 'assets/images/dummy/food/ristorante/zuppadiverdure.png',
    'product_price': 32000,
  },
  {
    'product_id': 3,
    'product_name': 'Bruschetta Integrale',
    'product_description': 'Roti gandum panggang dengan topping tomat segar dan rempah. Lezat sebagai hidangan pembuka sehat.',
    'product_image': 'assets/images/dummy/food/ristorante/bruschettaintegrale.png',
    'product_price': 28000,
  },
  {
    'product_id': 4,
    'product_name': 'Pasta Integrale al Pesto',
    'product_description': 'Pasta gandum utuh disajikan dengan saus pesto basil yang kaya rasa. Cocok untuk menu makan siang bergizi.',
    'product_image': 'assets/images/dummy/food/ristorante/pastaintegralealpesto.png',
    'product_price': 55000,
  },
  {
    'product_id': 5,
    'product_name': 'Grilled Salmon con Limone',
    'product_description': 'Ikan salmon panggang dibumbui dengan lemon dan rempah pilihan. Sumber protein sehat dan lezat.',
    'product_image': 'assets/images/dummy/food/ristorante/grilledsalmonconlimone.png',
    'product_price': 85000,
  },
  {
    'product_id': 6,
    'product_name': 'Risotto ai Funghi',
    'product_description': 'Risotto lembut dengan jamur dan keju parmesan. Nikmati cita rasa Italia yang kaya dan hangat.',
    'product_image': 'assets/images/dummy/food/ristorante/risottoaifunghi.png',
    'product_price': 58000,
  },
  {
    'product_id': 7,
    'product_name': 'Aqua Frizzante con Limone',
    'product_description': 'Air mineral berkarbonasi dengan irisan lemon segar. Minuman ringan yang menyegarkan tenggorokan.',
    'product_image': 'assets/images/dummy/food/ristorante/aquafrizzanteconlimone.png',
    'product_price': 18000,
  },
  {
    'product_id': 8,
    'product_name': 'Smoothie Frutti Rossi',
    'product_description': 'Smoothie segar dari campuran buah beri merah. Kaya akan antioksidan dan rasa manis alami.',
    'product_image': 'assets/images/dummy/food/ristorante/smoothiefruttirossi.png',
    'product_price': 32000,
  },
  {
    'product_id': 9,
    'product_name': 'Succo di Arancia Fresca',
    'product_description': 'Jus jeruk segar yang diperas langsung. Sumber vitamin C alami untuk daya tahan tubuh.',
    'product_image': 'assets/images/dummy/food/ristorante/succodiaranciafresca.png',
    'product_price': 25000,
  },
  {
    'product_id': 10,
    'product_name': 'Teh Hijau Dingin ala Italia',
    'product_description': 'Teh hijau dingin dengan sentuhan rasa citrus. Menyegarkan dan cocok diminum kapan saja.',
    'product_image': 'assets/images/dummy/food/ristorante/tehhijaudinginalaitalia.png',
    'product_price': 22000,
  },
    {
    'product_id': 11,
    'product_name': 'Paket Sayuran Buah',
    'product_description': 'Kombinasi segar sayur dan buah pilihan untuk kebutuhan harian Anda. Cocok untuk konsumsi keluarga setiap hari.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/paketsayuranbuah.png',
    'product_price': 40000,
  },
  {
    'product_id': 12,
    'product_name': 'Garam dan Madu',
    'product_description': 'Garam alami dan madu murni dalam satu paket sehat. Dapat digunakan untuk memasak dan pengobatan tradisional.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/garamdanmadu.png',
    'product_price': 35000,
  },
  {
    'product_id': 13,
    'product_name': 'Telur Ayam Kampung Lusinan',
    'product_description': 'Telur ayam kampung segar berisi 12 butir. Kaya protein dan nutrisi, baik untuk sarapan sehat.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/telurayamkampunglusinan.png',
    'product_price': 35000,
  },
  {
    'product_id': 14,
    'product_name': 'Beras Premium',
    'product_description': 'Beras kualitas premium dengan tekstur pulen. Cocok untuk berbagai jenis masakan Indonesia.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/beraspremium.png',
    'product_price': 30000,
  },
  {
    'product_id': 15,
    'product_name': 'Daging Salmon',
    'product_description': 'Potongan daging salmon segar, kaya omega-3. Baik untuk kesehatan jantung dan otak.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/dagingsalmon.png',
    'product_price': 85000,
  },
  {
    'product_id': 16,
    'product_name': 'Bawang Merah Kiloan',
    'product_description': 'Bawang merah segar dijual per kilogram. Wajib ada di dapur untuk bumbu dasar masakan.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/bawangmerahkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 17,
    'product_name': 'Mangga Harum Manis Kiloan',
    'product_description': 'Mangga harum manis segar per kilogram. Rasa manis alami dengan aroma yang menggugah selera.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/manggaharummaniskiloan.png',
    'product_price': 22000,
  },
  {
    'product_id': 18,
    'product_name': 'Pisang Ambon Sisir',
    'product_description': 'Satu sisir pisang ambon yang manis dan lembut. Ideal sebagai camilan sehat setiap hari.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/pisangambonsisir.png',
    'product_price': 20000,
  },
  {
    'product_id': 19,
    'product_name': 'Jeruk Sunkist Kiloan',
    'product_description': 'Jeruk sunkist segar kaya vitamin C dijual per kilogram. Segar untuk jus atau langsung dikonsumsi.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/jeruksunkistkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 20,
    'product_name': 'Wortel Kiloan',
    'product_description': 'Wortel segar dalam kemasan kiloan. Baik untuk kesehatan mata dan sistem imun.',
    'product_image': 'assets/images/dummy/ingredients/supermarketaja/wortelkiloan.png',
    'product_price': 12500,
  },
  {
    'product_id': 21,
    'product_name': 'Feijoada Sehat Vegan',
    'product_description': 'Feijoada versi sehat tanpa daging, menggunakan kacang hitam, sayuran rebus, dan rempah tradisional Brasil.',
    'product_image': 'assets/images/dummy/food/feijoadasehatvegan.png',
    'product_price': 38000,
  },
  {
    'product_id': 22,
    'product_name': 'Caipirinha Infused Detox',
    'product_description': 'Minuman dingin ala Caipirinha tanpa alkohol, infused dengan jeruk nipis, daun mint, dan madu murni.',
    'product_image': 'assets/images/dummy/food/caipirinhainfuseddetox.png',
    'product_price': 16000,
  },
  {
    'product_id': 23,
    'product_name': 'Pizza Sayur Gandum',
    'product_description': 'Pizza berbahan dasar gandum utuh dengan topping paprika, tomat ceri, jamur, dan keju rendah lemak.',
    'product_image': 'assets/images/dummy/food/ristorante/pizzasayurgandum.jpg',
    'product_price': 29000,
  },
  {
    'product_id': 24,
    'product_name': 'Spaghetti Zucchini Pesto',
    'product_description': 'Spaghetti dari zucchini spiral dengan saus pesto kemangi segar dan kacang pinus. Alternatif rendah karbohidrat.',
    'product_image': 'assets/images/dummy/food/ristorante/spaghettizucchinipesto.jpg',
    'product_price': 30000,
  },
  {
    'product_id': 25,
    'product_name': 'Beras 5kg',
    'product_description': 'Beras putih kualitas premium dengan tekstur pulen. Ideal untuk kebutuhan dapur keluarga.',
    'product_image': 'assets/images/dummy/food/beras5kg.png',
    'product_price': 72000,
  },
  {
    'product_id': 26,
    'product_name': 'Minyak Goreng 1L',
    'product_description': 'Minyak goreng kemasan 1 liter, cocok untuk memasak sehari-hari. Kualitas jernih dan hemat.',
    'product_image': 'assets/images/dummy/food/minyakgoreng1l.png',
    'product_price': 15000,
  },
  {
    'product_id': 27,
    'product_name': 'Chicken Katsu',
    'product_description': 'Ayam goreng tepung ala Jepang dengan tekstur renyah. Cocok disantap dengan saus tonkatsu.',
    'product_image': 'assets/images/dummy/food/umamihana/chickenkatsu.jpg',
    'product_price': 35000,
  },
  {
    'product_id': 28,
    'product_name': 'Salmon Sushi Roll',
    'product_description': 'Gulungan sushi berisi potongan salmon segar. Sajian Jepang yang lezat dan menggoda.',
    'product_image': 'assets/images/dummy/food/umamihana/salmonsushiroll.jpg',
    'product_price': 42000,
  },
  {
    'product_id': 29,
    'product_name': 'Telur Ayam 1 Dus',
    'product_description': 'Satu dus telur ayam segar berisi 12 butir. Sumber protein untuk berbagai hidangan.',
    'product_image': 'assets/images/dummy/food/telurayam1dus.png',
    'product_price': 28000,
  },
  {
    'product_id': 30,
    'product_name': 'Sayur Segar Pack',
    'product_description': 'Paket sayuran segar pilihan siap masak. Praktis dan menyehatkan untuk keluarga.',
    'product_image': 'assets/images/dummy/food/sayursegarpack.png',
    'product_price': 15000,
  },
  {
    'product_id': 31,
    'product_name': 'Cabai Merah 500g',
    'product_description': 'Cabai merah segar dalam kemasan 500 gram. Cocok untuk sambal atau bumbu masakan.',
    'product_image': 'assets/images/dummy/food/cabaimerah500g.png',
    'product_price': 8000,
  },
  {
    'product_id': 32,
    'product_name': 'Bawang Putih 250g',
    'product_description': 'Bawang putih kupas segar 250 gram. Wajib ada untuk bumbu dasar masakan harian.',
    'product_image': 'assets/images/dummy/food/bawangputih250g.png',
    'product_price': 5700,
  },
  {
    'product_id': 33,
    'product_name': 'Salmon Donburi',
    'product_description': 'Semangkuk nasi donburi dengan potongan salmon panggang dan sayuran segar.',
    'product_image': 'assets/images/dummy/food/umamihana/salmondonburi.jpg',
    'product_price': 45000,
  },
  {
    'product_id': 34,
    'product_name': 'Tofu Miso Soup',
    'product_description': 'Sup miso klasik Jepang dengan tahu sutra dan rumput laut wakame.',
    'product_image': 'assets/images/dummy/food/umamihana/tofumisosoup.jpg',
    'product_price': 18000,
  },
  {
    'product_id': 35,
    'product_name': 'Edamame Rebus',
    'product_description': 'Kacang edamame muda direbus, camilan sehat kaya protein nabati.',
    'product_image': 'assets/images/dummy/food/umamihana/edamamerebus.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 36,
    'product_name': 'Yasai Itame',
    'product_description': 'Tumis sayuran ala Jepang dengan saus ringan, cocok untuk diet sehat.',
    'product_image': 'assets/images/dummy/food/umamihana/yasaiitame.jpg',
    'product_price': 22000,
  },
  {
    'product_id': 37,
    'product_name': 'Onigiri Tuna',
    'product_description': 'Nasi kepal isi tuna sehat, dibalut nori, cocok sebagai camilan cepat.',
    'product_image': 'assets/images/dummy/food/umamihana/onigirituna.jpg',
    'product_price': 15000,
  },
  {
    'product_id': 38,
    'product_name': 'Soba Salad',
    'product_description': 'Salad soba dingin dengan sayur segar dan dressing wijen Jepang.',
    'product_image': 'assets/images/dummy/food/umamihana/sobasalad.jpg',
    'product_price': 28000,
  },
  {
    'product_id': 39,
    'product_name': 'Chawanmushi',
    'product_description': 'Puding telur kukus lembut khas Jepang dengan isian jamur dan udang.',
    'product_image': 'assets/images/dummy/food/umamihana/chawanmushi.jpg',
    'product_price': 20000,
  },
  {
    'product_id': 40,
    'product_name': 'Matcha Azuki Bowl',
    'product_description': 'Hidangan penutup sehat berisi kacang merah, jeli matcha, dan buah segar.',
    'product_image': 'assets/images/dummy/food/umamihana/matchaazukibowl.jpg',
    'product_price': 25000,
  },
  {
    'product_id': 41,
    'product_name': 'Tomat Segar 500g',
    'product_description': 'Tomat merah segar pilihan untuk masakan harian. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/tomatsegar500g.jpg',
    'product_price': 6000,
  },
  {
    'product_id': 42,
    'product_name': 'Bayam Hijau Ikat',
    'product_description': 'Bayam segar kaya zat besi, cocok untuk sayur bening atau tumis.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/bayamhijauikat.jpg',
    'product_price': 3500,
  },
  {
    'product_id': 43,
    'product_name': 'Kentang Lokal 1kg',
    'product_description': 'Kentang lokal serbaguna, bisa untuk goreng, kukus, atau sup.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/kentanglokal1kg.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 44,
    'product_name': 'Wortel Segar 500g',
    'product_description': 'Wortel manis dan renyah, kaya vitamin A. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/wortelsegar500g.jpg',
    'product_price': 7000,
  },
  {
    'product_id': 45,
    'product_name': 'Beras Medium 1kg',
    'product_description': 'Beras kualitas medium, pulen dan cocok untuk konsumsi harian.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/berasmedium1kg.jpg',
    'product_price': 13500,
  },
  {
    'product_id': 46,
    'product_name': 'Telur Ayam 6 Butir',
    'product_description': 'Telur ayam segar dari peternakan lokal. Isi 6 butir.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/telurayam6butir.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 47,
    'product_name': 'Cabai Merah 250g',
    'product_description': 'Cabai merah segar, pedas alami untuk bumbu dapur.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/cabaimerah250g.jpg',
    'product_price': 9500,
  },
  {
    'product_id': 48,
    'product_name': 'Bawang Merah 250g',
    'product_description': 'Bawang merah kupas segar, cocok untuk berbagai masakan.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/bawangmerah250g.png',
    'product_price': 8700,
  },
  {
    'product_id': 49,
    'product_name': 'Minyak Goreng 1L',
    'product_description': 'Minyak goreng kemasan 1 liter, jernih dan tidak mudah hitam.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/minyakgoreng1l.png',
    'product_price': 17000,
  },
  {
    'product_id': 50,
    'product_name': 'Garam Dapur 500g',
    'product_description': 'Garam halus untuk keperluan dapur sehari-hari. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/garamdapur500g.png',
    'product_price': 3000,
  },
  {
    'product_id': 51,
    'product_name': 'Açaí Bowl Tradicional',
    'product_description': 'Semangkuk açaí beku dengan topping granola, pisang, dan madu organik.',
    'product_image': 'assets/images/dummy/food/sabordosol/acaibowltradicional.png',
    'product_price': 32000,
  },
  {
    'product_id': 52,
    'product_name': 'Quinoa com Legumes',
    'product_description': 'Quinoa rebus dengan campuran sayur segar ala Brasil yang kaya serat.',
    'product_image': 'assets/images/dummy/food/sabordosol/quinoacomlegumes.png',
    'product_price': 28000,
  },
  {
    'product_id': 53,
    'product_name': 'Salada Tropical',
    'product_description': 'Campuran sayuran tropis segar, alpukat, dan saus jeruk nipis.',
    'product_image': 'assets/images/dummy/food/sabordosol/saladatropical.png',
    'product_price': 25000,
  },
  {
    'product_id': 54,
    'product_name': 'Moqueca de Legumes',
    'product_description': 'Versi sehat moqueca khas Brazil berbahan dasar sayuran dan santan ringan.',
    'product_image': 'assets/images/dummy/food/sabordosol/moquecadelegumes.png',
    'product_price': 35000,
  },
  {
    'product_id': 55,
    'product_name': 'Feijão Preto Fit',
    'product_description': 'Kacang hitam khas Brazil dimasak dengan sedikit minyak dan rempah alami.',
    'product_image': 'assets/images/dummy/food/sabordosol/feijaopretofit.png',
    'product_price': 22000,
  },
  {
    'product_id': 56,
    'product_name': 'Pão de Queijo Integral',
    'product_description': 'Roti keju dari tepung tapioka versi gandum utuh, rendah gluten.',
    'product_image': 'assets/images/dummy/food/sabordosol/paodequeijointegral.png',
    'product_price': 15000,
  },
  {
    'product_id': 57,
    'product_name': 'Tapioca com Coco',
    'product_description': 'Tapioka panggang isi kelapa parut dan sedikit gula aren.',
    'product_image': 'assets/images/dummy/food/sabordosol/tapiocacomcoco.png',
    'product_price': 18000,
  },
  {
    'product_id': 58,
    'product_name': 'Grilled Tilapia Brasil',
    'product_description': 'Ikan nila panggang dengan bumbu khas Brazil dan salad samping.',
    'product_image': 'assets/images/dummy/food/sabordosol/grilledtilapiabrasil.png',
    'product_price': 37000,
  },
  {
    'product_id': 59,
    'product_name': 'Smoothie Maracujá',
    'product_description': 'Smoothie buah markisa segar, tanpa tambahan gula.',
    'product_image': 'assets/images/dummy/food/sabordosol/smoothiemaracuja.png',
    'product_price': 20000,
  },
  {
    'product_id': 60,
    'product_name': 'Sopa de Abóbora Light',
    'product_description': 'Sup labu kuning lembut dengan rempah ringan dan krim nabati.',
    'product_image': 'assets/images/dummy/food/sabordosol/sopadeaboboralight.png',
    'product_price': 24000,
  },
];