final List<Map<String, dynamic>> productListTable = [
  {
    'product_id': 1,
    'product_name': 'Insalata Caprese',
    'product_description': 'Tomat segar, mozzarella, dan daun basil disiram minyak zaitun. Hidangan khas Italia yang ringan dan menyegarkan.',
    'product_image': 'assets/images/dummy/food/insalata_caprese.png',
    'product_price': 38000,
  },
  {
    'product_id': 2,
    'product_name': 'Zuppa di Verdure',
    'product_description': 'Sup sayur ala Italia dengan berbagai sayuran segar. Cocok untuk dinikmati saat cuaca dingin.',
    'product_image': 'assets/images/dummy/food/zuppa_di_verdure.png',
    'product_price': 32000,
  },
  {
    'product_id': 3,
    'product_name': 'Bruschetta Integrale',
    'product_description': 'Roti gandum panggang dengan topping tomat segar dan rempah. Lezat sebagai hidangan pembuka sehat.',
    'product_image': 'assets/images/dummy/food/bruschetta_integrale.png',
    'product_price': 28000,
  },
  {
    'product_id': 4,
    'product_name': 'Pasta Integrale al Pesto',
    'product_description': 'Pasta gandum utuh disajikan dengan saus pesto basil yang kaya rasa. Cocok untuk menu makan siang bergizi.',
    'product_image': 'assets/images/dummy/food/pasta_integrale_al_pesto.png',
    'product_price': 55000,
  },
  {
    'product_id': 5,
    'product_name': 'Grilled Salmon con Limone',
    'product_description': 'Ikan salmon panggang dibumbui dengan lemon dan rempah pilihan. Sumber protein sehat dan lezat.',
    'product_image': 'assets/images/dummy/food/grilled_salmon_con_limone.png',
    'product_price': 85000,
  },
  {
    'product_id': 6,
    'product_name': 'Risotto ai Funghi',
    'product_description': 'Risotto lembut dengan jamur dan keju parmesan. Nikmati cita rasa Italia yang kaya dan hangat.',
    'product_image': 'assets/images/dummy/food/risotto_ai_funghi.png',
    'product_price': 58000,
  },
  {
    'product_id': 7,
    'product_name': 'Aqua Frizzante con Limone',
    'product_description': 'Air mineral berkarbonasi dengan irisan lemon segar. Minuman ringan yang menyegarkan tenggorokan.',
    'product_image': 'assets/images/dummy/food/aqua_frizzante_con_limone.png',
    'product_price': 18000,
  },
  {
    'product_id': 8,
    'product_name': 'Smoothie Frutti Rossi',
    'product_description': 'Smoothie segar dari campuran buah beri merah. Kaya akan antioksidan dan rasa manis alami.',
    'product_image': 'assets/images/dummy/food/smoothie_frutti_rossi.png',
    'product_price': 32000,
  },
  {
    'product_id': 9,
    'product_name': 'Succo di Arancia Fresca',
    'product_description': 'Jus jeruk segar yang diperas langsung. Sumber vitamin C alami untuk daya tahan tubuh.',
    'product_image': 'assets/images/dummy/food/succo_di_arancia_fresca.png',
    'product_price': 25000,
  },
  {
    'product_id': 10,
    'product_name': 'Teh Hijau Dingin ala Italia',
    'product_description': 'Teh hijau dingin dengan sentuhan rasa citrus. Menyegarkan dan cocok diminum kapan saja.',
    'product_image': 'assets/images/dummy/food/teh_hijau_dingin_ala_italia.png',
    'product_price': 22000,
  },
    {
    'product_id': 11,
    'product_name': 'Paket Sayuran Buah',
    'product_description': 'Kombinasi segar sayur dan buah pilihan untuk kebutuhan harian Anda. Cocok untuk konsumsi keluarga setiap hari.',
    'product_image': 'assets/images/dummy/food/paketsayuranbuah.png',
    'product_price': 40000,
  },
  {
    'product_id': 12,
    'product_name': 'Garam dan Madu',
    'product_description': 'Garam alami dan madu murni dalam satu paket sehat. Dapat digunakan untuk memasak dan pengobatan tradisional.',
    'product_image': 'assets/images/dummy/food/garamdanmadu.png',
    'product_price': 35000,
  },
  {
    'product_id': 13,
    'product_name': 'Telur Ayam Kampung Lusinan',
    'product_description': 'Telur ayam kampung segar berisi 12 butir. Kaya protein dan nutrisi, baik untuk sarapan sehat.',
    'product_image': 'assets/images/dummy/food/telurayamkampunglusinan.png',
    'product_price': 35000,
  },
  {
    'product_id': 14,
    'product_name': 'Beras Premium',
    'product_description': 'Beras kualitas premium dengan tekstur pulen. Cocok untuk berbagai jenis masakan Indonesia.',
    'product_image': 'assets/images/dummy/food/beraspremium.png',
    'product_price': 30000,
  },
  {
    'product_id': 15,
    'product_name': 'Daging Salmon',
    'product_description': 'Potongan daging salmon segar, kaya omega-3. Baik untuk kesehatan jantung dan otak.',
    'product_image': 'assets/images/dummy/food/dagingsalmon.png',
    'product_price': 85000,
  },
  {
    'product_id': 16,
    'product_name': 'Bawang Merah Kiloan',
    'product_description': 'Bawang merah segar dijual per kilogram. Wajib ada di dapur untuk bumbu dasar masakan.',
    'product_image': 'assets/images/dummy/food/bawangmerahkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 17,
    'product_name': 'Mangga Harum Manis Kiloan',
    'product_description': 'Mangga harum manis segar per kilogram. Rasa manis alami dengan aroma yang menggugah selera.',
    'product_image': 'assets/images/dummy/food/manggaharummaniskiloan.png',
    'product_price': 22000,
  },
  {
    'product_id': 18,
    'product_name': 'Pisang Ambon Sisir',
    'product_description': 'Satu sisir pisang ambon yang manis dan lembut. Ideal sebagai camilan sehat setiap hari.',
    'product_image': 'assets/images/dummy/food/pisangambonsisir.png',
    'product_price': 20000,
  },
  {
    'product_id': 19,
    'product_name': 'Jeruk Sunkist Kiloan',
    'product_description': 'Jeruk sunkist segar kaya vitamin C dijual per kilogram. Segar untuk jus atau langsung dikonsumsi.',
    'product_image': 'assets/images/dummy/food/jeruksunkistkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 20,
    'product_name': 'Wortel Kiloan',
    'product_description': 'Wortel segar dalam kemasan kiloan. Baik untuk kesehatan mata dan sistem imun.',
    'product_image': 'assets/images/dummy/food/wortelkiloan.png',
    'product_price': 12500,
  },
  {
    'product_id': 21,
    'product_name': 'Feijoada Completa',
    'product_description': 'Hidangan khas Brasil yang kaya rasa dengan campuran daging dan kacang hitam. Cocok untuk makan siang yang mengenyangkan.',
    'product_image': 'assets/images/dummy/food/feijoadacompleta.png',
    'product_price': 45000,
  },
  {
    'product_id': 22,
    'product_name': 'Caipirinha Tradisional',
    'product_description': 'Minuman segar dengan rasa khas jeruk nipis dan gula tebu. Cocok dinikmati saat cuaca panas.',
    'product_image': 'assets/images/dummy/food/caipirinhatradisional.png',
    'product_price': 18000,
  },
  {
    'product_id': 23,
    'product_name': 'Pizza Margherita',
    'product_description': 'Pizza klasik Italia dengan topping tomat, keju mozzarella, dan daun basil. Favorit semua kalangan.',
    'product_image': 'assets/images/dummy/food/pizzamargherita.png',
    'product_price': 28000,
  },
  {
    'product_id': 24,
    'product_name': 'Spaghetti Carbonara',
    'product_description': 'Spaghetti dengan saus creamy dan taburan daging asap. Makanan khas Italia yang menggugah selera.',
    'product_image': 'assets/images/dummy/food/spaghetticarbonara.png',
    'product_price': 28000,
  },
  {
    'product_id': 25,
    'product_name': 'Beras 5kg',
    'product_description': 'Beras putih kualitas premium dengan tekstur pulen. Ideal untuk kebutuhan dapur keluarga.',
    'product_image': 'assets/images/dummy/food/beras5kg.png',
    'product_price': 72000,
  },
  {
    'product_id': 26,
    'product_name': 'Minyak Goreng 1L',
    'product_description': 'Minyak goreng kemasan 1 liter, cocok untuk memasak sehari-hari. Kualitas jernih dan hemat.',
    'product_image': 'assets/images/dummy/food/minyakgoreng1l.png',
    'product_price': 15000,
  },
  {
    'product_id': 27,
    'product_name': 'Chicken Katsu',
    'product_description': 'Ayam goreng tepung ala Jepang dengan tekstur renyah. Cocok disantap dengan saus tonkatsu.',
    'product_image': 'assets/images/dummy/food/chickenkatsu.png',
    'product_price': 35000,
  },
  {
    'product_id': 28,
    'product_name': 'Salmon Sushi Roll',
    'product_description': 'Gulungan sushi berisi potongan salmon segar. Sajian Jepang yang lezat dan menggoda.',
    'product_image': 'assets/images/dummy/food/salmonsushiroll.png',
    'product_price': 42000,
  },
  {
    'product_id': 29,
    'product_name': 'Telur Ayam 1 Dus',
    'product_description': 'Satu dus telur ayam segar berisi 12 butir. Sumber protein untuk berbagai hidangan.',
    'product_image': 'assets/images/dummy/food/telurayam1dus.png',
    'product_price': 28000,
  },
  {
    'product_id': 30,
    'product_name': 'Sayur Segar Pack',
    'product_description': 'Paket sayuran segar pilihan siap masak. Praktis dan menyehatkan untuk keluarga.',
    'product_image': 'assets/images/dummy/food/sayursegarpack.png',
    'product_price': 15000,
  },
  {
    'product_id': 31,
    'product_name': 'Cabai Merah 500g',
    'product_description': 'Cabai merah segar dalam kemasan 500 gram. Cocok untuk sambal atau bumbu masakan.',
    'product_image': 'assets/images/dummy/food/cabaimerah500g.png',
    'product_price': 8000,
  },
  {
    'product_id': 32,
    'product_name': 'Bawang Putih 250g',
    'product_description': 'Bawang putih kupas segar 250 gram. Wajib ada untuk bumbu dasar masakan harian.',
    'product_image': 'assets/images/dummy/food/bawangputih250g.png',
    'product_price': 5700,
  },
];