final List<Map<String, dynamic>> productListTable = [
  {
    'product_id': 1,
    'product_name': 'Insalata Caprese',
    'product_description': 'Tomat segar, mozzarella, dan daun basil disiram minyak zaitun. Hidangan khas Italia yang ringan dan menyegarkan.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/insalatacaprese.png',
    'product_price': 38000,
  },
  {
    'product_id': 2,
    'product_name': 'Zuppa di Verdure',
    'product_description': 'Sup sayur ala Italia dengan berbagai sayuran segar. Cocok untuk dinikmati saat cuaca dingin.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/zuppadiverdure.png',
    'product_price': 32000,
  },
  {
    'product_id': 3,
    'product_name': 'Bruschetta Integrale',
    'product_description': 'Roti gandum panggang dengan topping tomat segar dan rempah. Lezat sebagai hidangan pembuka sehat.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/bruschettaintegrale.png',
    'product_price': 28000,
  },
  {
    'product_id': 4,
    'product_name': 'Pasta Integrale al Pesto',
    'product_description': 'Pasta gandum utuh disajikan dengan saus pesto basil yang kaya rasa. Cocok untuk menu makan siang bergizi.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/pastaintegralealpesto.png',
    'product_price': 55000,
  },
  {
    'product_id': 5,
    'product_name': 'Grilled Salmon con Limone',
    'product_description': 'Ikan salmon panggang dibumbui dengan lemon dan rempah pilihan. Sumber protein sehat dan lezat.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/grilledsalmonconlimone.png',
    'product_price': 85000,
  },
  {
    'product_id': 6,
    'product_name': 'Risotto ai Funghi',
    'product_description': 'Risotto lembut dengan jamur dan keju parmesan. Nikmati cita rasa Italia yang kaya dan hangat.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/risottoaifunghi.png',
    'product_price': 58000,
  },
  {
    'product_id': 7,
    'product_name': 'Aqua Frizzante con Limone',
    'product_description': 'Air mineral berkarbonasi dengan irisan lemon segar. Minuman ringan yang menyegarkan tenggorokan.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/aquafrizzanteconlimone.png',
    'product_price': 18000,
  },
  {
    'product_id': 8,
    'product_name': 'Smoothie Frutti Rossi',
    'product_description': 'Smoothie segar dari campuran buah beri merah. Kaya akan antioksidan dan rasa manis alami.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/smoothiefruttirossi.png',
    'product_price': 32000,
  },
  {
    'product_id': 9,
    'product_name': 'Succo di Arancia Fresca',
    'product_description': 'Jus jeruk segar yang diperas langsung. Sumber vitamin C alami untuk daya tahan tubuh.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/succodiaranciafresca.png',
    'product_price': 25000,
  },
  {
    'product_id': 10,
    'product_name': 'Teh Hijau Dingin ala Italia',
    'product_description': 'Teh hijau dingin dengan sentuhan rasa citrus. Menyegarkan dan cocok diminum kapan saja.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/tehhijaudinginalaitalia.png',
    'product_price': 22000,
  },
  {
    'product_id': 11,
    'product_name': 'Paket Sayuran Buah',
    'product_description': 'Kombinasi segar sayur dan buah pilihan untuk kebutuhan harian Anda. Cocok untuk konsumsi keluarga setiap hari.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/paketsayuranbuah.png',
    'product_price': 40000,
  },
  {
    'product_id': 12,
    'product_name': 'Garam dan Madu',
    'product_description': 'Garam alami dan madu murni dalam satu paket sehat. Dapat digunakan untuk memasak dan pengobatan tradisional.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/garamdanmadu.png',
    'product_price': 35000,
  },
  {
    'product_id': 13,
    'product_name': 'Telur Ayam Kampung Lusinan',
    'product_description': 'Telur ayam kampung segar berisi 12 butir. Kaya protein dan nutrisi, baik untuk sarapan sehat.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/telurayamkampunglusinan.png',
    'product_price': 35000,
  },
  {
    'product_id': 14,
    'product_name': 'Beras Premium',
    'product_description': 'Beras kualitas premium dengan tekstur pulen. Cocok untuk berbagai jenis masakan Indonesia.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/beraspremium.png',
    'product_price': 30000,
  },
  {
    'product_id': 15,
    'product_name': 'Daging Salmon',
    'product_description': 'Potongan daging salmon segar, kaya omega-3. Baik untuk kesehatan jantung dan otak.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/dagingsalmon.png',
    'product_price': 85000,
  },
  {
    'product_id': 16,
    'product_name': 'Bawang Merah Kiloan',
    'product_description': 'Bawang merah segar dijual per kilogram. Wajib ada di dapur untuk bumbu dasar masakan.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/bawangmerahkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 17,
    'product_name': 'Mangga Harum Manis Kiloan',
    'product_description': 'Mangga harum manis segar per kilogram. Rasa manis alami dengan aroma yang menggugah selera.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/manggaharummaniskiloan.png',
    'product_price': 22000,
  },
  {
    'product_id': 18,
    'product_name': 'Pisang Ambon Sisir',
    'product_description': 'Satu sisir pisang ambon yang manis dan lembut. Ideal sebagai camilan sehat setiap hari.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/pisangambonsisir.png',
    'product_price': 20000,
  },
  {
    'product_id': 19,
    'product_name': 'Jeruk Sunkist Kiloan',
    'product_description': 'Jeruk sunkist segar kaya vitamin C dijual per kilogram. Segar untuk jus atau langsung dikonsumsi.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/jeruksunkistkiloan.png',
    'product_price': 35000,
  },
  {
    'product_id': 20,
    'product_name': 'Wortel Kiloan',
    'product_description': 'Wortel segar dalam kemasan kiloan. Baik untuk kesehatan mata dan sistem imun.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/wortelkiloan.png',
    'product_price': 12500,
  },
  {
    'product_id': 21,
    'product_name': 'Feijoada Sehat Vegan',
    'product_description': 'Feijoada versi sehat tanpa daging, menggunakan kacang hitam, sayuran rebus, dan rempah tradisional Brasil.',
    'product_image': 'assets/images/dummy/food/verdebrasil/feijoadasehatvegan.png',
    'product_price': 38000,
  },
  {
    'product_id': 22,
    'product_name': 'Caipirinha Infused Detox',
    'product_description': 'Minuman dingin ala Caipirinha tanpa alkohol, infused dengan jeruk nipis, daun mint, dan madu murni.',
    'product_image': 'assets/images/dummy/food/verdebrasil/caipirinhainfuseddetox.png',
    'product_price': 16000,
  },
  {
    'product_id': 23,
    'product_name': 'Pizza Sayur Gandum',
    'product_description': 'Pizza berbahan dasar gandum utuh dengan topping paprika, tomat ceri, jamur, dan keju rendah lemak.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/pizzasayurgandum.jpg',
    'product_price': 29000,
  },
  {
    'product_id': 24,
    'product_name': 'Spaghetti Zucchini Pesto',
    'product_description': 'Spaghetti dari zucchini spiral dengan saus pesto kemangi segar dan kacang pinus. Alternatif rendah karbohidrat.',
    'product_image': 'assets/images/dummy/food/verduraitaliana/spaghettizucchinipesto.jpg',
    'product_price': 30000,
  },
  {
    'product_id': 25,
    'product_name': 'Oatmeal Organik',
    'product_description': 'Oatmeal organik utuh bebas pengawet. Cocok untuk sarapan sehat tinggi serat dan rendah gula.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/oatmealorganik.png',
    'product_price': 45000,
  },
  {
    'product_id': 26,
    'product_name': 'Kacang Almond Panggang',
    'product_description': 'Almond panggang tanpa garam tambahan. Cemilan sehat kaya protein dan lemak baik.',
    'product_image': 'assets/images/dummy/ingredients/supermarketharmoni/kacangalmondpanggang.png',
    'product_price': 55000,
  },
  {
    'product_id': 27,
    'product_name': 'Chicken Katsu',
    'product_description': 'Ayam goreng tepung ala Jepang dengan tekstur renyah. Cocok disantap dengan saus tonkatsu.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/chickenkatsu.jpg',
    'product_price': 35000,
  },
  {
    'product_id': 28,
    'product_name': 'Salmon Sushi Roll',
    'product_description': 'Gulungan sushi berisi potongan salmon segar. Sajian Jepang yang lezat dan menggoda.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/salmonsushiroll.jpg',
    'product_price': 42000,
  },
  {
    'product_id': 29,
    'product_name': 'Sayur Segar Pack',
    'product_description': 'Paket sayuran segar pilihan siap masak. Praktis dan menyehatkan untuk keluarga.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/sayursegarpack.png',
    'product_price': 50000,
  },
  {
    'product_id': 30,
    'product_name': 'Bayam Segar 1 Ikat',
    'product_description': 'Satu ikat bayam hijau segar, kaya zat besi dan serat. Cocok untuk tumisan dan sup sehat.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/bayamsegar1ikat.png',
    'product_price': 17500,
  },
  {
    'product_id': 31,
    'product_name': 'Cabai Merah 500g',
    'product_description': 'Cabai merah segar dalam kemasan 500 gram. Cocok untuk sambal atau bumbu masakan.',
    'product_image': 'assets/images/dummy/food/cabaimerah500g.png',
    'product_price': 8000,
  },
  {
    'product_id': 32,
    'product_name': 'Bawang Putih 250g',
    'product_description': 'Bawang putih kupas segar 250 gram. Wajib ada untuk bumbu dasar masakan harian.',
    'product_image': 'assets/images/dummy/food/bawangputih250g.png',
    'product_price': 5700,
  },
  {
    'product_id': 33,
    'product_name': 'Salmon Donburi',
    'product_description': 'Semangkuk nasi donburi dengan potongan salmon panggang dan sayuran segar.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/salmondonburi.jpg',
    'product_price': 45000,
  },
  {
    'product_id': 34,
    'product_name': 'Tofu Miso Soup',
    'product_description': 'Sup miso klasik Jepang dengan tahu sutra dan rumput laut wakame.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/tofumisosoup.jpg',
    'product_price': 18000,
  },
  {
    'product_id': 35,
    'product_name': 'Edamame Rebus',
    'product_description': 'Kacang edamame muda direbus, camilan sehat kaya protein nabati.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/edamamerebus.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 36,
    'product_name': 'Yasai Itame',
    'product_description': 'Tumis sayuran ala Jepang dengan saus ringan, cocok untuk diet sehat.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/yasaiitame.jpg',
    'product_price': 22000,
  },
  {
    'product_id': 37,
    'product_name': 'Onigiri Tuna',
    'product_description': 'Nasi kepal isi tuna sehat, dibalut nori, cocok sebagai camilan cepat.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/onigirituna.jpg',
    'product_price': 15000,
  },
  {
    'product_id': 38,
    'product_name': 'Soba Salad',
    'product_description': 'Salad soba dingin dengan sayur segar dan dressing wijen Jepang.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/sobasalad.jpg',
    'product_price': 28000,
  },
  {
    'product_id': 39,
    'product_name': 'Chawanmushi',
    'product_description': 'Puding telur kukus lembut khas Jepang dengan isian jamur dan udang.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/chawanmushi.jpg',
    'product_price': 20000,
  },
  {
    'product_id': 40,
    'product_name': 'Matcha Azuki Bowl',
    'product_description': 'Hidangan penutup sehat berisi kacang merah, jeli matcha, dan buah segar.',
    'product_image': 'assets/images/dummy/food/aozorasehatkitchen/matchaazukibowl.jpg',
    'product_price': 25000,
  },
  {
    'product_id': 41,
    'product_name': 'Tomat Segar 500g',
    'product_description': 'Tomat merah segar pilihan untuk masakan harian. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/tomatsegar500g.jpg',
    'product_price': 6000,
  },
  {
    'product_id': 42,
    'product_name': 'Bayam Hijau Ikat',
    'product_description': 'Bayam segar kaya zat besi, cocok untuk sayur bening atau tumis.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/bayamhijauikat.jpg',
    'product_price': 3500,
  },
  {
    'product_id': 43,
    'product_name': 'Kentang Lokal 1kg',
    'product_description': 'Kentang lokal serbaguna, bisa untuk goreng, kukus, atau sup.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/kentanglokal1kg.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 44,
    'product_name': 'Wortel Segar 500g',
    'product_description': 'Wortel manis dan renyah, kaya vitamin A. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/wortelsegar500g.jpg',
    'product_price': 7000,
  },
  {
    'product_id': 45,
    'product_name': 'Beras Medium 1kg',
    'product_description': 'Beras kualitas medium, pulen dan cocok untuk konsumsi harian.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/berasmedium1kg.jpg',
    'product_price': 13500,
  },
  {
    'product_id': 46,
    'product_name': 'Telur Ayam 6 Butir',
    'product_description': 'Telur ayam segar dari peternakan lokal. Isi 6 butir.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/telurayam6butir.jpg',
    'product_price': 12000,
  },
  {
    'product_id': 47,
    'product_name': 'Cabai Merah 250g',
    'product_description': 'Cabai merah segar, pedas alami untuk bumbu dapur.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/cabaimerah250g.jpg',
    'product_price': 9500,
  },
  {
    'product_id': 48,
    'product_name': 'Bawang Merah 250g',
    'product_description': 'Bawang merah kupas segar, cocok untuk berbagai masakan.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/bawangmerah250g.png',
    'product_price': 8700,
  },
  {
    'product_id': 49,
    'product_name': 'Minyak Goreng 1L',
    'product_description': 'Minyak goreng kemasan 1 liter, jernih dan tidak mudah hitam.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/minyakgoreng1l.png',
    'product_price': 17000,
  },
  {
    'product_id': 50,
    'product_name': 'Garam Dapur 500g',
    'product_description': 'Garam halus untuk keperluan dapur sehari-hari. Berat ±500 gram.',
    'product_image': 'assets/images/dummy/ingredients/pasarmurah/garamdapur500g.png',
    'product_price': 3000,
  },
  {
    'product_id': 51,
    'product_name': 'Açaí Bowl Tradicional',
    'product_description': 'Semangkuk açaí beku dengan topping granola, pisang, dan madu organik.',
    'product_image': 'assets/images/dummy/food/verdebrasil/acaibowltradicional.png',
    'product_price': 32000,
  },
  {
    'product_id': 52,
    'product_name': 'Quinoa com Legumes',
    'product_description': 'Quinoa rebus dengan campuran sayur segar ala Brasil yang kaya serat.',
    'product_image': 'assets/images/dummy/food/verdebrasil/quinoacomlegumes.png',
    'product_price': 28000,
  },
  {
    'product_id': 53,
    'product_name': 'Salada Tropical',
    'product_description': 'Campuran sayuran tropis segar, alpukat, dan saus jeruk nipis.',
    'product_image': 'assets/images/dummy/food/verdebrasil/saladatropical.png',
    'product_price': 25000,
  },
  {
    'product_id': 54,
    'product_name': 'Moqueca de Legumes',
    'product_description': 'Versi sehat moqueca khas Brazil berbahan dasar sayuran dan santan ringan.',
    'product_image': 'assets/images/dummy/food/verdebrasil/moquecadelegumes.png',
    'product_price': 35000,
  },
  {
    'product_id': 55,
    'product_name': 'Feijão Preto Fit',
    'product_description': 'Kacang hitam khas Brazil dimasak dengan sedikit minyak dan rempah alami.',
    'product_image': 'assets/images/dummy/food/verdebrasil/feijaopretofit.png',
    'product_price': 22000,
  },
  {
    'product_id': 56,
    'product_name': 'Pão de Queijo Integral',
    'product_description': 'Roti keju dari tepung tapioka versi gandum utuh, rendah gluten.',
    'product_image': 'assets/images/dummy/food/verdebrasil/paodequeijointegral.png',
    'product_price': 15000,
  },
  {
    'product_id': 57,
    'product_name': 'Tapioca com Coco',
    'product_description': 'Tapioka panggang isi kelapa parut dan sedikit gula aren.',
    'product_image': 'assets/images/dummy/food/verdebrasil/tapiocacomcoco.png',
    'product_price': 18000,
  },
  {
    'product_id': 58,
    'product_name': 'Grilled Tilapia Brasil',
    'product_description': 'Ikan nila panggang dengan bumbu khas Brazil dan salad samping.',
    'product_image': 'assets/images/dummy/food/verdebrasil/grilledtilapiabrasil.png',
    'product_price': 37000,
  },
  {
    'product_id': 59,
    'product_name': 'Smoothie Maracujá',
    'product_description': 'Smoothie buah markisa segar, tanpa tambahan gula.',
    'product_image': 'assets/images/dummy/food/verdebrasil/smoothiemaracuja.png',
    'product_price': 20000,
  },
  {
    'product_id': 60,
    'product_name': 'Sopa de Abóbora Light',
    'product_description': 'Sup labu kuning lembut dengan rempah ringan dan krim nabati.',
    'product_image': 'assets/images/dummy/food/verdebrasil/sopadeaboboralight.png',
    'product_price': 24000,
  },
  {
    'product_id': 61,
    'product_name': 'Salad Quinoa Pelangi',
    'product_description': 'Salad warna-warni dengan quinoa, paprika, alpukat, tomat ceri, dan dressing lemon.',
    'product_image': 'assets/images/dummy/food/glowkitchen/saladquinoapelangi.png',
    'product_price': 42000,
  },
  {
    'product_id': 62,
    'product_name': 'Smoothie Hijau Detox',
    'product_description': 'Campuran bayam, nanas, apel hijau, lemon dan chia seed. Menyegarkan dan membersihkan tubuh.',
    'product_image': 'assets/images/dummy/food/glowkitchen/smoothiehijaudetox.png',
    'product_price': 38000,
  },
  {
    'product_id': 63,
    'product_name': 'Wrap Tempe Panggang',
    'product_description': 'Roti gandum isi tempe panggang, selada, wortel, dan saus tahini homemade.',
    'product_image': 'assets/images/dummy/food/glowkitchen/wraptempepanggang.png',
    'product_price': 45000,
  },
  {
    'product_id': 64,
    'product_name': 'Nasi Merah Buddha Bowl',
    'product_description': 'Bowl berisi nasi merah, brokoli kukus, wortel, edamame, dan kacang mete.',
    'product_image': 'assets/images/dummy/food/glowkitchen/nasimerahbuddhabowl.png',
    'product_price': 47000,
  },
  {
    'product_id': 65,
    'product_name': 'Jus Beet & Lemon Zing',
    'product_description': 'Minuman segar dari bit, lemon, jahe, dan madu organik.',
    'product_image': 'assets/images/dummy/food/glowkitchen/jusbeetlemonzing.png',
    'product_price': 32000,
  },
  {
    'product_id': 66,
    'product_name': 'Tofu Curry Bowl',
    'product_description': 'Tahu panggang dengan saus kari santan ringan, sayuran rebus, dan nasi basmati.',
    'product_image': 'assets/images/dummy/food/glowkitchen/tofucurrybowl.png',
    'product_price': 46000,
  },
  {
    'product_id': 67,
    'product_name': 'Oatmeal Kurma & Pisang',
    'product_description': 'Oatmeal hangat dengan topping pisang, kurma, kacang almond, dan kayu manis.',
    'product_image': 'assets/images/dummy/food/glowkitchen/oatmealkurmapisang.png',
    'product_price': 39000,
  },
  {
    'product_id': 68,
    'product_name': 'Infused Water Jeruk & Mint',
    'product_description': 'Air mineral dengan irisan jeruk segar, daun mint, dan timun.',
    'product_image': 'assets/images/dummy/food/glowkitchen/infusedwaterjerukmint.png',
    'product_price': 20000,
  },
  {
    'product_id': 69,
    'product_name': 'Avocado Cacao Pudding',
    'product_description': 'Puding alpukat dan kakao, manis alami dari madu dan topping kacang-kacangan.',
    'product_image': 'assets/images/dummy/food/glowkitchen/avocadocacaopudding.png',
    'product_price': 42000,
  },
  {
    'product_id': 70,
    'product_name': 'Teh Herbal Hangat Glow',
    'product_description': 'Campuran teh hijau, serai, jahe, dan madu organik untuk relaksasi.',
    'product_image': 'assets/images/dummy/food/glowkitchen/tehherbalhangatglow.png',
    'product_price': 28000,
  },
  {
    'product_id': 71,
    'product_name': 'Fruit Rainbow Bowl',
    'product_description': 'Bowl buah warna-warni berisi stroberi, mangga, kiwi, blueberry, dan anggur, disajikan dengan yogurt rendah lemak.',
    'product_image': 'assets/images/dummy/food/sehatbang/fruitrainbowbowl.png',
    'product_price': 42000,
  },
  {
    'product_id': 72,
    'product_name': 'Tropical Smoothie Blend',
    'product_description': 'Smoothie tropis segar dari campuran nanas, pisang, jeruk, dan air kelapa.',
    'product_image': 'assets/images/dummy/food/sehatbang/tropicalsmoothieblend.png',
    'product_price': 36000,
  },
  {
    'product_id': 73,
    'product_name': 'Mango Chia Parfait',
    'product_description': 'Parfait mangga dengan lapisan chia pudding, granola, dan potongan buah segar.',
    'product_image': 'assets/images/dummy/food/sehatbang/mangochiaparfait.png',
    'product_price': 39000,
  },
  {
    'product_id': 74,
    'product_name': 'Berry Burst Juice',
    'product_description': 'Jus segar dari campuran stroberi, raspberry, blueberry, dan sedikit lemon.',
    'product_image': 'assets/images/dummy/food/sehatbang/berryburstjuice.png',
    'product_price': 34000,
  },
  {
    'product_id': 75,
    'product_name': 'Frozen Banana Pops',
    'product_description': 'Pisang beku celup dark chocolate, ditaburi kacang cincang dan kelapa parut.',
    'product_image': 'assets/images/dummy/food/sehatbang/frozenbananapops.png',
    'product_price': 28000,
  },
  {
    'product_id': 76,
    'product_name': 'Dragon Fruit Smoothie Bowl',
    'product_description': 'Smoothie bowl dari buah naga dengan topping granola, kelapa kering, dan irisan pisang.',
    'product_image': 'assets/images/dummy/food/sehatbang/dragonfruitsmoothiebowl.png',
    'product_price': 45000,
  },
  {
    'product_id': 77,
    'product_name': 'Citrus Fruit Salad',
    'product_description': 'Salad buah segar dari jeruk, grapefruit, lemon, dan delima, dengan saus madu-lime.',
    'product_image': 'assets/images/dummy/food/sehatbang/citrusfruitsalad.png',
    'product_price': 39000,
  },
  {
    'product_id': 78,
    'product_name': 'Watermelon Mint Refresher',
    'product_description': 'Minuman segar dari semangka, daun mint, dan es batu, cocok untuk cuaca panas.',
    'product_image': 'assets/images/dummy/food/sehatbang/watermelonmintrefresher.png',
    'product_price': 31000,
  },
  {
    'product_id': 79,
    'product_name': 'Apple Yogurt Crunch',
    'product_description': 'Irisan apel hijau dengan yogurt dan topping kacang walnut serta madu.',
    'product_image': 'assets/images/dummy/food/sehatbang/appleyogurtcrunch.png',
    'product_price': 34000,
  },
  {
    'product_id': 80,
    'product_name': 'Kiwi Pineapple Splash',
    'product_description': 'Minuman campuran kiwi dan nanas yang manis dan menyegarkan.',
    'product_image': 'assets/images/dummy/food/sehatbang/kiwipineapplesplash.png',
    'product_price': 32000,
  },
  {
    'product_id': 81,
    'product_name': 'Bayam Organik',
    'product_description': 'Sayuran hijau kaya zat besi dan serat, ideal untuk sup atau tumisan.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/bayamorganik.png',
    'product_price': 12000,
  },
  {
    'product_id': 82,
    'product_name': 'Kale Segar',
    'product_description': 'Daun kale segar dan renyah, cocok untuk salad atau jus detoks.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/kalesegar.png',
    'product_price': 18000,
  },
  {
    'product_id': 83,
    'product_name': 'Selada Romaine',
    'product_description': 'Selada segar dengan tekstur renyah, cocok untuk sandwich dan salad.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/seladaromaine.png',
    'product_price': 15000,
  },
  {
    'product_id': 84,
    'product_name': 'Pakcoy Hijau',
    'product_description': 'Sayuran oriental dengan rasa lembut, kaya vitamin dan mineral.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/pakcoyhijau.png',
    'product_price': 10000,
  },
  {
    'product_id': 85,
    'product_name': 'Sawi Hijau Lokal',
    'product_description': 'Sawi hijau segar hasil pertanian lokal tanpa pestisida.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/sawihijaulokal.png',
    'product_price': 9000,
  },
  {
    'product_id': 86,
    'product_name': 'Mentimun Organik',
    'product_description': 'Mentimun segar bebas pestisida, ideal untuk infused water atau lalapan.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/mentimunorganik.png',
    'product_price': 8000,
  },
  {
    'product_id': 87,
    'product_name': 'Jus Sayur Hijau',
    'product_description': 'Minuman segar dari kale, bayam, dan timun tanpa gula tambahan.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/jussayurhijau.png',
    'product_price': 22000,
  },
  {
    'product_id': 88,
    'product_name': 'Smoothie Detox Hijau',
    'product_description': 'Smoothie dari buah dan sayur hijau, membantu detoksifikasi tubuh.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/smoothiedetoxhijau.png',
    'product_price': 25000,
  },
  {
    'product_id': 89,
    'product_name': 'Lettuce Butterhead',
    'product_description': 'Selada jenis butterhead lembut dan enak untuk salad.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/lettucebutterhead.png',
    'product_price': 16000,
  },
  {
    'product_id': 90,
    'product_name': 'Brokoli Segar',
    'product_description': 'Brokoli organik segar kaya vitamin C dan serat, cocok untuk kukus dan tumis.',
    'product_image': 'assets/images/dummy/ingredients/harvestmart/brokolisegar.png',
    'product_price': 17000,
  },
  {
    'product_id': 91,
    'product_name': 'Oatmeal Instant Organik',
    'product_description': 'Oatmeal instan tinggi serat dan tanpa gula tambahan. Cocok untuk sarapan sehat.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/oatmealinstantorganik.png',
    'product_price': 28000,
  },
  {
    'product_id': 92,
    'product_name': 'Granola Madu Almond',
    'product_description': 'Granola renyah dengan madu alami dan potongan almond. Sumber energi harian.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/granolamadualmond.png',
    'product_price': 32000,
  },
  {
    'product_id': 93,
    'product_name': 'Chia Seed Superfood',
    'product_description': 'Chia seed kaya omega-3 dan serat. Cocok untuk smoothies atau topping yogurt.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/chiaseedsuperfood.png',
    'product_price': 25000,
  },
  {
    'product_id': 94,
    'product_name': 'Quinoa Putih Premium',
    'product_description': 'Quinoa putih pilihan, tinggi protein nabati. Cocok untuk pengganti nasi.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/quinoaputihpremium.png',
    'product_price': 36000,
  },
  {
    'product_id': 95,
    'product_name': 'Muesli Buah Kering',
    'product_description': 'Campuran oat, kismis, dan buah kering. Ideal untuk sarapan sehat.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/mueslibuahkering.png',
    'product_price': 29000,
  },
  {
    'product_id': 96,
    'product_name': 'Tepung Almond Organik',
    'product_description': 'Tepung almond bebas gluten dan tinggi protein, cocok untuk baking sehat.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/tepungalmondorganik.png',
    'product_price': 45000,
  },
  {
    'product_id': 97,
    'product_name': 'Biji Bunga Matahari',
    'product_description': 'Biji bunga matahari tinggi vitamin E, bisa digunakan untuk salad atau camilan.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/bijibungamatahari.png',
    'product_price': 22000,
  },
  {
    'product_id': 98,
    'product_name': 'Protein Bar Cokelat',
    'product_description': 'Camilan sehat berprotein tinggi dengan rasa cokelat alami.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/proteinbarcokelat.png',
    'product_price': 17000,
  },
  {
    'product_id': 99,
    'product_name': 'Kacang Almond Panggang',
    'product_description': 'Almond panggang tanpa garam, kaya lemak sehat dan protein.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/kacangalmondpanggang.png',
    'product_price': 34000,
  },
  {
    'product_id': 100,
    'product_name': 'Serbuk Matcha Jepang',
    'product_description': 'Bubuk matcha asli Jepang, tinggi antioksidan. Cocok untuk minuman sehat.',
    'product_image': 'assets/images/dummy/ingredients/fitmarket/serbukmatchajepang.png',
    'product_price': 39000,
  },
  {
    'product_id': 101,
    'product_name': 'Salad Bowl Segar',
    'product_description': 'Campuran sayur segar siap saji dalam mangkuk, cocok untuk makan siang sehat.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/saladbowlsegar.png',
    'product_price': 23000,
  },
  {
    'product_id': 102,
    'product_name': 'Buah Potong Mix Pack',
    'product_description': 'Paket buah potong segar berisi semangka, melon, dan pepaya dalam kemasan praktis.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/buahpotongmixpack.png',
    'product_price': 18000,
  },
  {
    'product_id': 103,
    'product_name': 'Edamame Rebus',
    'product_description': 'Edamame rebus dalam kemasan siap santap, tinggi protein nabati dan serat.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/edamamerebus.png',
    'product_price': 16000,
  },
  {
    'product_id': 104,
    'product_name': 'Snack Rumput Laut Panggang',
    'product_description': 'Camilan sehat dari rumput laut panggang rendah kalori dan gurih alami.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/snackrumputlautpanggang.png',
    'product_price': 12000,
  },
  {
    'product_id': 105,
    'product_name': 'Yogurt Greek Plain',
    'product_description': 'Yogurt greek tanpa tambahan gula, cocok untuk diet tinggi protein.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/yogurtgreekplain.png',
    'product_price': 21000,
  },
  {
    'product_id': 106,
    'product_name': 'Roti Gandum Utuh',
    'product_description': 'Roti dari gandum utuh kaya serat, cocok untuk sarapan sehat dan kenyang lebih lama.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/rotigandumutuh.png',
    'product_price': 19000,
  },
  {
    'product_id': 107,
    'product_name': 'Minuman Kefir Fermentasi',
    'product_description': 'Minuman fermentasi dari susu berkultur, tinggi probiotik untuk kesehatan pencernaan.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/minumankefirfermentasi.png',
    'product_price': 25000,
  },
  {
    'product_id': 108,
    'product_name': 'Wrap Sayur dan Ayam',
    'product_description': 'Wrap siap santap berisi sayuran segar dan ayam tanpa lemak, praktis dan sehat.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/wrapsayurdanayam.png',
    'product_price': 27000,
  },
  {
    'product_id': 109,
    'product_name': 'Sup Krim Brokoli',
    'product_description': 'Sup krim brokoli siap santap dalam kemasan praktis. Tanpa pengawet.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/supkrimbrokoli.png',
    'product_price': 22000,
  },
  {
    'product_id': 110,
    'product_name': 'Smoothie Bowl Berry',
    'product_description': 'Smoothie bowl dari buah berry dan topping granola, kaya antioksidan.',
    'product_image': 'assets/images/dummy/ingredients/zestmart/smoothiebowlberry.png',
    'product_price': 30000,
  },
  {
    'product_id': 111,
    'product_name': 'Urap Sayur Sehat',
    'product_description': 'Sayuran kukus seperti bayam, kacang panjang, dan tauge, disajikan dengan kelapa parut berbumbu.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/urapsayursehat.png',
    'product_price': 34000,
  },
  {
    'product_id': 112,
    'product_name': 'Gado-Gado Vegan',
    'product_description': 'Gado-gado khas Betawi dengan saus kacang tanpa terasi dan tambahan tempe panggang.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/gadogadovegan.png',
    'product_price': 37000,
  },
  {
    'product_id': 113,
    'product_name': 'Pecel Daun Kelor',
    'product_description': 'Pecel khas Jawa dengan daun kelor kukus, sambal kacang sehat, dan rempeyek tipis.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/peceldaunkelor.png',
    'product_price': 36000,
  },
  {
    'product_id': 114,
    'product_name': 'Tumis Jamur Rempah',
    'product_description': 'Tumis jamur tiram dan jamur kuping dengan serai, jahe, dan sedikit minyak kelapa.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/tumisjamurrempah.png',
    'product_price': 35000,
  },
  {
    'product_id': 115,
    'product_name': 'Sup Jagung Bening',
    'product_description': 'Sup jagung manis, wortel, dan daun seledri dengan kuah kaldu sayur bening.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/supjagungbening.png',
    'product_price': 32000,
  },
  {
    'product_id': 116,
    'product_name': 'Nasi Merah Ayam Serundeng',
    'product_description': 'Nasi merah disajikan dengan ayam kampung kukus dan serundeng kelapa tanpa goreng.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/nasimerahayamserundeng.png',
    'product_price': 45000,
  },
  {
    'product_id': 117,
    'product_name': 'Sayur Asem Segar',
    'product_description': 'Sayur asem khas Jawa Tengah dengan jagung, labu siam, dan kacang panjang.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/sayurasemsegar.png',
    'product_price': 33000,
  },
  {
    'product_id': 118,
    'product_name': 'Teh Pandan Rempah',
    'product_description': 'Teh herbal dari daun pandan, cengkeh, dan kayu manis. Tanpa gula tambahan.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/tehpandanrempah.png',
    'product_price': 28000,
  },
  {
    'product_id': 119,
    'product_name': 'Jamu Kunyit Asam Dingin',
    'product_description': 'Minuman tradisional dingin yang menyegarkan, dari kunyit segar dan asam Jawa.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/jamukunyitasamdingin.png',
    'product_price': 30000,
  },
  {
    'product_id': 120,
    'product_name': 'Puding Santan Gula Merah',
    'product_description': 'Puding lembut dari santan dan agar-agar, disiram kuah gula merah wangi pandan.',
    'product_image': 'assets/images/dummy/food/dapursehatnusantara/pudingsantangulamerah.png',
    'product_price': 32000,
  },
];