const List<Map<String, dynamic>> chatDummyData = [
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #1',
    'message': 'Terima kasih banyak, makanannya sudah saya terima',
    'datetime': '23/05',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #2',
    'message': 'Thank you, Sukses terus ya!',
    'datetime': '21/05',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #3',
    'message': 'Makanannya sudah sampai',
    'datetime': '18/05',
    'numberMessageReceived': 1,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #4',
    'message': 'Terima kasih! Semoga rezekinya lancar hari ini.',
    'datetime': '12/05',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #5',
    'message': 'Sama-sama! Selamat menikmati makanannya!',
    'datetime': '07/05',
    'numberMessageReceived': 1,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #6',
    'message': 'Terima kasih sudah diantar',
    'datetime': '30/04',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #7',
    'message': 'Mantap bang :D',
    'datetime': '11/04',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #8',
    'message': 'Makasih ya Bang, jaga kesehatan selalu!',
    'datetime': '11/04',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #9',
    'message': 'Terima kasih banyak. Semoga harimu penuh berkah!',
    'datetime': '08/04',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #10',
    'message': 'Udah diterima dengan baik. Makasih ya :D',
    'datetime': '02/04',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #11',
    'message': 'Sama-sama! Selamat menikmati makanannya!',
    'datetime': '29/03',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #12',
    'message': 'Pengantarannya oke banget.',
    'datetime': '22/03',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #13',
    'message': 'Hati-hati di jalan.',
    'datetime': '13/03',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #14',
    'message': 'Makanannya udah diterima, makasih.',
    'datetime': '13/03',
    'numberMessageReceived': null,
  },
  {
    'profileImage': 'assets/images/dummy/chat/driver.png',
    'driverName': 'Driver #15',
    'message': 'Makasi bang, Semoga orderanmu rame terus!',
    'datetime': '11/03',
    'numberMessageReceived': null,
  },
];