const List<Map<String, dynamic>> discountRestaurant = [
  {
    'image': 'assets/images/dummy/restaurant/sabordosol.png',
    'name': 'Sabor do Sol',
    'type': 'discount',
    'rate': 4.7,
    'location': 2.18,
    'percentage': 25,
  },
  {
    'image': 'assets/images/dummy/restaurant/rasanusantara.png',
    'name': 'Rasa Nusantara',
    'type': 'discount',
    'rate': 4.2,
    'location': 1.11,
    'percentage': 25,
  },
  {
    'image': 'assets/images/dummy/restaurant/ristorantecabang.png',
    'name': 'Ristorante Cabangan',
    'type': 'discount',
    'rate': 4.3,
    'location': 5.17,
    'percentage': 15,
  },
  {
    'image': 'assets/images/dummy/restaurant/sehatbang.png',
    'name': 'sehatBang',
    'type': 'discount',
    'rate': 4.5,
    'location': 2.48,
    'percentage': 20,
  },
  {
    'image': 'assets/images/dummy/restaurant/linaelit.png',
    'name': 'Lina Elit Healthy Resto',
    'type': 'discount',
    'rate': 4.3,
    'location': 4.55,
    'percentage': 30,
  },
];

const List<Map<String, dynamic>> freeShipmentRestaurant = [
  {
    'image': 'assets/images/dummy/restaurant/umamihana.png',
    'name': 'Umami Hana Restaurant',
    'rate': 4.8,
    'location': 4.11,
    'type': 'freeshipment',
  },
  {
    'image': 'assets/images/dummy/restaurant/glowkitchen.png',
    'name': 'Glow Kitchen',
    'rate': 4.7,
    'location': 2.11,
    'type': 'freeshipment',
  },
  {
    'image': 'assets/images/dummy/restaurant/greenspoon.png',
    'name': 'Green Spoon',
    'rate': 4.2,
    'location': 0.91,
    'type': 'freeshipment',
  },
  {
    'image': 'assets/images/dummy/restaurant/lepapillonbleu.png',
    'name': 'Le Pappillon Blue',
    'rate': 4.7,
    'location': 0.68,
    'type': 'freeshipment',
  },
  {
    'image': 'assets/images/dummy/restaurant/sehatku.png',
    'name': 'Sehatku',
    'rate': 4.9,
    'location': 4.56,
    'type': 'freeshipment',
  },
];