List<Map<String, dynamic>> doneHistoryList = [
  {
    'id': 1,
    'orderDate': DateTime(2025, 3, 27, 14, 50),
    'driverName': 'Driver #4',
    'businessName': 'Sabor do Sol',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/sabordosol.png',
    'addressReceiver': 'Jl. Matahari No. 5',
    'orderList': [
      {
        'name': 'Feijoada Completa',
        'quantity': 1,
        'price': 45000,
        'notes': '',
      },
      {
        'name': 'Caipirinha Tradicional',
        'quantity': 2,
        'price': 18000,
        'notes': '',
      },
    ],
    'serviceFee': 5000,
    'deliveryFee': 10000,
    'paymentMethod': 'Kartu Kredit',
    'cardType': 'done',
  },
  {
    'id': 2,
    'orderDate': DateTime(2025, 3, 26, 11, 24),
    'driverName': 'Driver #5',
    'businessName': 'Ristorante',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/ristorante.png',
    'addressReceiver': 'Jl. Lorem Ipsum 1 No. 2',
    'orderList': [
      {
        'name': 'Pizza Margherita',
        'quantity': 2,
        'price': 28000,
        'notes': 'Tanpa bawang',
      },
      {
        'name': 'Spaghetti Carbonara',
        'quantity': 1,
        'price': 28000,
        'notes': 'Extra keju',
      },
    ],
    'serviceFee': 5600,
    'deliveryFee': 10000,
    'paymentMethod': 'Kartu Kredit',
    'cardType': 'done',
  },
  {
    'id': 3,
    'orderDate': DateTime(2025, 3, 25, 14, 51),
    'businessName': 'Supermarket Aja',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/supermarketaja.png',
    'driverName': 'Driver #1',
    'addressReceiver': 'Jl. Belanja No. 12',
    'orderList': [
      {
        'name': 'Beras 5kg',
        'quantity': 1,
        'price': 72000,
        'notes': '',
      },
      {
        'name': 'Minyak Goreng 1L',
        'quantity': 2,
        'price': 15000,
        'notes': '',
      },
    ],
    'serviceFee': 3000,
    'deliveryFee': 5000,
    'paymentMethod': 'COD',
    'cardType': 'done',
  },
  {
    'id': 4,
    'orderDate': DateTime(2025, 3, 24, 13, 39),
    'businessName': 'Umami Hana Restaurant',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/umamihana.png',
    'driverName': 'Driver #3',
    'addressReceiver': 'Jl. Sakura Indah No. 88',
    'orderList': [
      {
        'name': 'Chicken Katsu',
        'quantity': 1,
        'price': 35000,
        'notes': 'Tanpa saus',
      },
      {
        'name': 'Salmon Sushi Roll',
        'quantity': 1,
        'price': 42000,
        'notes': '',
      },
    ],
    'serviceFee': 3050,
    'deliveryFee': 4000,
    'paymentMethod': 'GoPay',
    'cardType': 'done',
  },
  {
    'id': 5,
    'orderDate': DateTime(2025, 3, 23, 6, 49),
    'businessName': 'HarvestMart Supermarket',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/harvestmart.png',
    'driverName': 'Driver #6',
    'addressReceiver': 'Jl. Panen Raya No. 7',
    'orderList': [
      {
        'name': 'Telur Ayam 1 Dus',
        'quantity': 1,
        'price': 28000,
        'notes': '',
      },
      {
        'name': 'Sayur Segar Pack',
        'quantity': 1,
        'price': 15000,
        'notes': '',
      },
    ],
    'serviceFee': 2000,
    'deliveryFee': 5000,
    'paymentMethod': 'QRIS',
    'cardType': 'done',
  },
  {
    'id': 6,
    'orderDate': DateTime(2025, 3, 20, 8, 12),
    'businessName': 'Pasar Famgro',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/famgro.png',
    'driverName': 'Driver #2',
    'addressReceiver': 'Jl. Tradisional No. 10',
    'orderList': [
      {
        'name': 'Cabai Merah 500g',
        'quantity': 1,
        'price': 8000,
        'notes': '',
      },
      {
        'name': 'Bawang Putih 250g',
        'quantity': 1,
        'price': 5700,
        'notes': '',
      },
    ],
    'serviceFee': 1000,
    'deliveryFee': 3000,
    'paymentMethod': 'Tunai',
    'cardType': 'done',
  },
];

List<Map<String, dynamic>> ongoingHistoryList = [
  {
    'id': 1,
    'orderDate': DateTime(2025, 3, 27, 17, 00),
    'businessName': 'Ristorante',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/ristorante.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Pizza Margherita',
        'quantity': 1,
        'price': 45000,
        'notes': '',
      },
      {
        'name': 'Spaghetti Bolognese',
        'quantity': 1,
        'price': 23400,
        'notes': '',
      },
    ],
    'serviceFee': 1000,
    'deliveryFee': 2000,
    'paymentMethod': 'Tunai',
    'cardType': 'diproses',
  },
  {
    'id': 2,
    'orderDate': DateTime(2025, 3, 27, 16, 55),
    'businessName': 'Supermarket Aja',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/supermarketaja.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Minyak Goreng 1L',
        'quantity': 1,
        'price': 20000,
        'notes': '',
      },
      {
        'name': 'Gula Pasir 1kg',
        'quantity': 1,
        'price': 20000,
        'notes': '',
      },
    ],
    'serviceFee': 1000,
    'deliveryFee': 3000,
    'paymentMethod': 'Tunai',
    'cardType': 'diproses',
  },
  {
    'id': 3,
    'orderDate': DateTime(2025, 3, 27, 16, 50),
    'businessName': 'Ristorante',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/ristorante.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Lasagna',
        'quantity': 2,
        'price': 61000,
        'notes': 'Tanpa keju',
      },
    ],
    'serviceFee': 1500,
    'deliveryFee': 2500,
    'paymentMethod': 'OVO',
    'cardType': 'diproses',
  },
  {
    'id': 4,
    'orderDate': DateTime(2025, 3, 27, 16, 40),
    'businessName': 'Ristorante',
    'businessType': 'Restaurant',
    'businessImage': 'assets/images/dummy/restaurant/ristorante.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Pasta Carbonara',
        'quantity': 1,
        'price': 40000,
        'notes': '',
      },
    ],
    'serviceFee': 1000,
    'deliveryFee': 2000,
    'paymentMethod': 'QRIS',
    'cardType': 'dikirim',
  },
  {
    'id': 5,
    'orderDate': DateTime(2025, 3, 25, 16, 30),
    'businessName': 'Supermarket Aja',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/supermarketaja.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Telur Ayam 1kg',
        'quantity': 1,
        'price': 30000,
        'notes': '',
      },
    ],
    'serviceFee': 1000,
    'deliveryFee': 3000,
    'paymentMethod': 'Tunai',
    'cardType': 'diproses',
  },
  {
    'id': 6,
    'orderDate': DateTime(2025, 3, 25, 16, 20),
    'businessName': 'Supermarket Aja',
    'businessType': 'Market',
    'businessImage': 'assets/images/dummy/market/supermarketaja.png',
    'driverName': 'Driver #5',
    'addressReceiver': 'Jl. Sehat Bahagia 2 No. 10',
    'orderList': [
      {
        'name': 'Air Mineral 600ml',
        'quantity': 2,
        'price': 5000,
        'notes': '',
      },
    ],
    'serviceFee': 500,
    'deliveryFee': 2500,
    'paymentMethod': 'GoPay',
    'cardType': 'dikirim',
  },
];